Repository woowacourse-teams/2024-devel-up, pull requests merged in 2024-11, with the labels that each got.

#757 플라이웨이 외래키 제약으로 init 안되는 오류 수정 (issue #756)
  backend/src/main/resources/db/migration/V1__init.sql
Labels: 🚛 백엔드, 🐛 버그

#762 README 이미지 및 컨텐츠 추가 (issue #753)
  README.md
Labels: 📋 문서

#764 랜딩 페이지 화면 크기에 따른 컴포넌트 크기 조절 및 디자인 이슈 수정 (issue #763)
  frontend/src/App.styled.ts
  frontend/src/hooks/useScrollComponent.ts
  frontend/src/index.tsx
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#766 미션, 디스커션 제출 로직 리팩터링 (issue #765)
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/hooks/useDiscussion.ts
  frontend/src/hooks/useFormSubmission.ts
  frontend/src/hooks/useInitializeInputs.ts
  frontend/src/hooks/useSubmitDiscussionHandlers.ts
  frontend/src/hooks/useSubmitDiscussionMutation.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/hooks/useSubmitSolutionHandlers.ts
  frontend/src/hooks/useUpdateDiscussion.ts
  frontend/src/hooks/useUpdateSolution.ts
  frontend/src/mocks/Discussion.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/MissionSubmitPage/MissionSubmitPage.styled.ts
  frontend/src/pages/MissionSubmitPage/index.tsx
  frontend/src/types/solution.ts
Labels: 🎨 프론트엔드, 🚀 개선

#768 dev서버 api 주소 변경 (issue #767)
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#769 dev 개발 서버 api 재변경(issue #767)
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, 🐛 버그
