Repository woowacourse-teams/2024-devel-up, pull requests merged in 2024-10, with the labels that each got.

#584 롬복 의존성 추가 (issue #581)
  backend/build.gradle
  backend/scripts/healthcheck.sh
Labels: 🚛 백엔드, 🚀 개선

#589 백엔드 대규모 리팩터링 (issue #582)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentWriteService.java
  backend/src/main/java/develup/application/member/MemberResponse.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionComment.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepository.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionHashTags.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
  backend/src/test/java/develup/api/DiscussionCommentApiTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentGroupingServiceTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentReadServiceTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentWriteServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
  backend/src/test/java/develup/domain/discussion/comment/DiscussionCommentRepositoryTest.java
  backend/src/test/java/develup/domain/discussion/comment/DiscussionCommentTest.java
  backend/src/test/java/develup/domain/mission/MissionHashTagsTest.java
Labels: 🚛 백엔드, 🚀 개선

#594 lombok 적용 (issue #583)
  backend/src/main/java/develup/api/AuthApi.java
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/api/DiscussionCommentApi.java
  backend/src/main/java/develup/api/HashTagApi.java
  backend/src/main/java/develup/api/MemberApi.java
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/api/auth/AuthArgumentResolver.java
  backend/src/main/java/develup/api/common/CookieUtils.java
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/api/exception/GlobalExceptionHandler.java
  backend/src/main/java/develup/api/logging/LoggingFilter.java
  backend/src/main/java/develup/application/auth/AuthService.java
  backend/src/main/java/develup/application/auth/oauth/OAuthContext.java
  backend/src/main/java/develup/application/auth/oauth/OAuthService.java
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/DiscussionWriteService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentWriteService.java
  backend/src/main/java/develup/application/hashtag/HashTagReadService.java
  backend/src/main/java/develup/application/member/MemberReadService.java
  backend/src/main/java/develup/application/member/MemberWriteService.java
  backend/src/main/java/develup/application/mission/MissionReadService.java
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/application/solution/SolutionWriteService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentWriteService.java
  backend/src/main/java/develup/domain/CreatedAtAuditableEntity.java
  backend/src/main/java/develup/domain/IdentifiableEntity.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTag.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTagId.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
  backend/src/main/java/develup/domain/discussion/Title.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionComment.java
  backend/src/main/java/develup/domain/hashtag/HashTag.java
  backend/src/main/java/develup/domain/member/Member.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionHashTag.java
  backend/src/main/java/develup/domain/mission/MissionHashTags.java
  backend/src/main/java/develup/domain/mission/MissionUrl.java
  backend/src/main/java/develup/domain/solution/PullRequestUrl.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/Title.java
  backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
  backend/src/main/java/develup/infra/auth/oauth/github/GithubOAuthStrategy.java
Labels: 🚛 백엔드, 🚀 개선

#595 미션 없을 때, 해시태그 없을 때 디스커션 조회 버그 수정 및 테스트 코드 추가 (issue #588)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/test/java/develup/application/discussion/DiscussionReadServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#591 디스커션/솔루션 당 부모 댓글 개수 조회하도록 수정 (issue #587)
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/application/discussion/comment/MyDiscussionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/MySolutionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentCounts.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepository.java
  backend/src/main/java/develup/domain/discussion/comment/MyDiscussionComment.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/comment/MySolutionComment.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentCount.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentCounts.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentReadServiceTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentReadServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
Labels: 🚛 백엔드, 🐛 버그

#592 디스커션, 솔루션 Title 길이 검증 로직 추가 (Issue #586)
  backend/src/main/java/develup/application/discussion/DiscussionWriteService.java
  backend/src/main/java/develup/application/solution/SubmitSolutionRequest.java
  backend/src/main/java/develup/application/solution/UpdateSolutionRequest.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionTitle.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionSubmit.java
  backend/src/main/java/develup/domain/solution/SolutionTitle.java
  backend/src/main/java/develup/infra/auth/oauth/github/GithubOAuthClient.java
  backend/src/test/java/develup/application/discussion/DiscussionReadServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionTitleTest.java
  backend/src/test/java/develup/domain/solution/SolutionTest.java
  backend/src/test/java/develup/domain/solution/SolutionTitleTest.java
  backend/src/test/java/develup/support/data/DiscussionTestData.java
  backend/src/test/java/develup/support/data/SolutionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#509 개발 서버 배포 실패 시 롤백하도록 수정 및 알림 정책 수정 (issue #508)
  .github/workflows/backend_dev_cd.yml
  backend/scripts/dev_healthcheck.sh
Labels: 🚛 백엔드, 🐛 버그

#492 디스커션 수정 기능 구현 (issue #472)
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/discussion/DiscussionWriteService.java
  backend/src/main/java/develup/application/discussion/UpdateDiscussionRequest.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
  backend/src/test/java/develup/application/discussion/DiscussionWriteServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#600 백엔드 DEV CD 스크립트 오타 수정 (issue #599)
  .github/workflows/backend_dev_cd.yml
Labels: 🚛 백엔드, 🐛 버그

#604 fix: 스크립트 변경 롤백 (issue #602)
  .github/workflows/backend_dev_cd.yml
Labels: 🚛 백엔드, 🐛 버그

#603 Query dsl 설정(issue #601)
  backend/build.gradle
  backend/src/main/java/develup/api/config/QueryDslConfig.java
Labels: 🚛 백엔드, ⚒️ 기능

#611 솔루션 Querydsl 적용
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/application/solution/SolutionWriteService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryCustomTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, 🚀 개선

#616 디스커션 댓글 QueryDSL 적용(issue #614)
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepository.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustom.java
  backend/src/test/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#621 미션에 QueryDSL 도입 (issue #605)
  backend/src/main/java/develup/application/mission/MissionReadService.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/mission/MissionRepositoryCustom.java
  backend/src/test/java/develup/domain/mission/MissionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#607 솔루션 댓글에 Querydsl 적용 (issue #606)
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepositoryCustom.java
  backend/src/test/java/develup/application/solution/SolutionWriteServiceTest.java
  backend/src/test/java/develup/domain/solution/comment/SolutionCommentRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#618 디스커션, 풀이 글 수정 및 삭제 기능 추가 (issue #597)
  frontend/src/apis/discussionAPI.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/CommentSection/CommentSection.styled.ts
  frontend/src/components/DiscussionDetail/DiscussionDetail.styled.ts
  frontend/src/components/DiscussionDetail/DiscussionDetailBottom.tsx
  frontend/src/components/DiscussionDetail/DiscussionDetailHeader.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/ModalContent/ConfirmButtons/ConfirmButtons.styled.ts
  frontend/src/components/ModalContent/ConfirmButtons/index.tsx
  frontend/src/components/SolutionDetail/SolutionDetailBottom.tsx
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/SolutionDetail/SolutionSection.styled.ts
  frontend/src/components/SolutionDetail/index.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/constants/variants.ts
  frontend/src/hooks/useDiscussion.ts
  frontend/src/hooks/useDiscussionDelete.ts
  frontend/src/hooks/useSolution.ts
  frontend/src/hooks/useSolutionDelete.ts
  frontend/src/hooks/useUpdateDiscussion.ts
  frontend/src/hooks/useUpdateSolution.ts
  frontend/src/mocks/Solutions.json
  frontend/src/mocks/handlers.ts
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/SolutionDetailPage/SolutionDetailPage.styled.ts
  frontend/src/pages/SolutionDetailPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#623 댓글 수정/삭제 버그 수정
  frontend/src/apis/solutions.ts
  frontend/src/components/CommentSection/index.tsx
  frontend/src/components/DiscussionDetail/DiscussionDetailBottom.tsx
  frontend/src/hooks/usePatchDiscussionComment.ts
  frontend/src/hooks/usePatchSolutionComment.ts
Labels: 🐛 버그

#612 디스커션 QueryDSL 적용 (issue #608)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/DiscussionWriteService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepositoryCustom.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#627 디스커션, 풀이 수정, 제출 풀이 수정, 제출 버그 해결 (issue #624)
  frontend/src/components/DiscussionDetail/DiscussionDetail.styled.ts
  frontend/src/components/DiscussionDetail/DiscussionDetailHeader.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/hooks/useSubmitDiscussion.ts
  frontend/src/hooks/useUpdateDiscussion.ts
  frontend/src/hooks/useUpdateSolution.ts
  frontend/src/mocks/Discussion.json
  frontend/src/mocks/Discussions.json
  frontend/src/mocks/Solutions.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missions.json
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#630 에러페이지 디자인 (issue #629)
  frontend/src/assets/images/error.svg
  frontend/src/assets/images/error_not_found.svg
  frontend/src/components/common/Error/ErrorFallback.styled.ts
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/constants/api.ts
  frontend/src/index.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LoginPage/LoginPage.styled.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#631 런칭 전 각종 수정사항 반영 (feat/#619)
  frontend/index.html
  frontend/public/favicon.ico
  frontend/public/logo.svg
  frontend/src/App.tsx
  frontend/src/assets/images/develupLogo.png
  frontend/src/assets/images/logo.svg
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/components/Footer/Footer.styled.ts
  frontend/src/components/Footer/index.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/hooks/__tests__/useSingleRequestMutation.test.tsx
  frontend/src/hooks/useSingleRequestMutation.ts
  frontend/src/hooks/useSubmitDiscussionMutation.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그, 🚀 개선

#637 디스커션 리스트에서 내용도 보이게 수정 (issue #635)
  backend/src/main/java/develup/application/discussion/SummarizedDiscussionResponse.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
Labels: 🚛 백엔드, 🚀 개선

#638 대시보드에서 댓글 조회 시 댓글 수 삭제 (issue #633)
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/application/discussion/comment/MyDiscussionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/MySolutionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentCounts.java
  backend/src/test/java/develup/api/DiscussionCommentApiTest.java
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentReadServiceTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentReadServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#641 대시보드 DESC 정렬 (issue #632)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/application/mission/MissionReadService.java
  backend/src/main/java/develup/application/solution/MySolutionResponse.java
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepositoryCustom.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustom.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepositoryCustom.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/db/migration/V2__add_solution_submitted_at.sql
  backend/src/test/java/develup/application/mission/MissionReadServiceTest.java
  backend/src/test/java/develup/application/solution/SolutionReadServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryCustomTest.java
  backend/src/test/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustomTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
  backend/src/test/java/develup/domain/solution/comment/SolutionCommentRepositoryCustomTest.java
  backend/src/test/java/develup/support/data/SolutionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#639 솔루션, 디스커션 삭제 버그 수정
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/main/resources/db/migration/V3__remove_comment_foreign_key.sql
  backend/src/test/java/develup/domain/solution/SolutionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🐛 버그

#645 홍보 전 QA반영 (feat/#644)
  frontend/index.html
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/DashBoard/DashboardDiscussion/DiscussionItem.tsx
  frontend/src/components/DashBoard/MyComments/MyComment.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/ModalContent/MissionProcess/MissionProcess.styled.ts
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/components/common/Error/ErrorLogo.tsx
  frontend/src/hooks/useLogoutMutation.ts
  frontend/src/hooks/useMissionStartMutation.ts
  frontend/src/index.tsx
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MainPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능, 🚀 개선

#646 런칭 전 수정사항 반영 (issue #640)
  frontend/src/App.tsx
  frontend/src/apis/solutions.ts
  frontend/src/assets/images/noContent.svg
  frontend/src/assets/images/upArrow.svg
  frontend/src/components/DiscussionDetail/DiscussionDetailHeader.tsx
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/DiscussionList/DiscussionListHeader.tsx
  frontend/src/components/DiscussionSubmit/DiscussionDescription.tsx
  frontend/src/components/DiscussionSubmit/DiscussionSubmit.styled.ts
  frontend/src/components/DiscussionSubmit/DiscussionSubmitHeader.tsx
  frontend/src/components/DiscussionSubmit/DiscussionTitle.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/SolutionList/SolutionList.styled.ts
  frontend/src/components/SolutionList/index.tsx
  frontend/src/components/common/LoadingSpinner/LoadingSpinner.styled.ts
  frontend/src/components/common/NoContent/NoContent.styled.ts
  frontend/src/components/common/NoContent/NoContentWithoutButton.tsx
  frontend/src/components/common/ScrollToTopButton/ScrollToTopButton.styled.ts
  frontend/src/components/common/ScrollToTopButton/index.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagList/TagList.styled.ts
  frontend/src/components/common/TagList/index.tsx
  frontend/src/components/common/TagMultipleList/TagMultipleList.styled.ts
  frontend/src/components/common/TagMultipleList/index.tsx
  frontend/src/constants/messages.ts
  frontend/src/hooks/useDescription.ts
  frontend/src/hooks/useDiscussionTitle.ts
  frontend/src/hooks/useSolutionSummaries.ts
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/DiscussionSubmitPage/DiscussionSubmitPage.styled.ts
  frontend/src/pages/DiscussionSubmitPage/index.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/types/mission.ts
Labels: 🎨 프론트엔드, 🐛 버그

#651 각종 수정 사항 반영 (feat#650)
  backend/src/main/java/develup/domain/member/.Provider.java.icloud
  frontend/index.html
  frontend/src/components/Footer/Footer.styled.ts
  frontend/src/components/Footer/index.tsx
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/styles/GlobalLayout.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능

#655 홍보 전 수정사항 반영
  frontend/index.html
  frontend/public/logo.svg
  frontend/src/components/Footer/Footer.styled.ts
Labels: 🎨 프론트엔드, ⚒️ 기능, 🚀 개선

#654 불필요한 파일 삭제 (issue #653)
  backend/src/main/java/develup/domain/member/.Provider.java.icloud
Labels: 🚛 백엔드

#658 푸터 width 수정 (issue #656)
  frontend/src/components/Footer/Footer.styled.ts
Labels: 🎨 프론트엔드, ⚒️ 기능, 🚀 개선

#663 풀이 태그 버그 해결 (issue #661)
  frontend/src/apis/solutions.ts
  frontend/src/pages/SolutionListPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#667 풀이 제출 일자로 정렬 안되는 버그 수정 (issue #666)
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🐛 버그

#676 솔루션, 디스커션 목록 조회 할 때 해시태그 필터링 시 조회 결과에 해당 해시태그만 표시되는 버그 수정(issue #674)
  backend/src/main/java/develup/domain/discussion/DiscussionRepositoryCustom.java
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryCustomTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🐛 버그

#685 솔루션 목록 조회에 페이지네이션 적용(issue #680)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/test/java/develup/application/solution/SolutionReadServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#690 사용자가 작성한 디스커션 댓글 페이지네이션 적용 (Issue #682)
  backend/src/main/java/develup/api/DiscussionCommentApi.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustom.java
  backend/src/test/java/develup/domain/discussion/comment/DiscussionCommentRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#691 디스커션 목록 페이지네이션 (issue #679)
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepositoryCustom.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#693 대시보드 제출한 풀이 페이지네이션 (issue #692)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/domain/solution/SolutionRepositoryCustom.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryCustomTest.java
Labels: 🚛 백엔드, 🚀 개선

#688 lombok.config 설정 추가 (Issue #598)
  backend/lombok.config
  backend/src/main/java/develup/domain/IdentifiableEntity.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTag.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTagId.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionComment.java
  backend/src/main/java/develup/domain/hashtag/HashTag.java
  backend/src/main/java/develup/domain/member/Member.java
  backend/src/main/java/develup/domain/mission/MissionHashTag.java
  backend/src/main/java/develup/domain/mission/MissionUrl.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
  backend/src/test/java/develup/domain/discussion/DiscussionTest.java
Labels: 🚛 백엔드, 🚀 개선

#694 풀이/디스커션 제출 페이지 마크다운 에디터 적용 (issue #683)
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/DiscussionSubmit/DiscussionDescription.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/MissionSubmit/OneWord.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/components/common/MarkdownEditor/TextArea.styled.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/SpinnerSuspense.tsx
  frontend/src/hooks/useDescription.ts
  frontend/src/hooks/useSubmitDiscussion.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 🎨 프론트엔드

#696 웹 페이지 접근성 헤더 적용 및 mediaQueries 추가 (issue #675)
  frontend/src/App.styled.ts
  frontend/src/App.tsx
  frontend/src/assets/images/rocket.svg
  frontend/src/components/Footer/Footer.styled.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/common/Error/ErrorFallback.styled.ts
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/styles/GlobalLayout.tsx
  frontend/src/styles/mediaQueries.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#698 페이지네이션 구현 (issue #684)
  frontend/src/apis/dashboardAPI.ts
  frontend/src/apis/discussionAPI.ts
  frontend/src/apis/discussionCommentAPI.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paginationAPI.ts
  frontend/src/apis/solutionCommentAPI.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/DashBoard/DashboardDiscussion/index.tsx
  frontend/src/components/DashBoard/DiscussionComment/index.tsx
  frontend/src/components/DashBoard/MyComments/MyCommentList.tsx
  frontend/src/components/DashBoard/SubmittedSolutions/index.tsx
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/SolutionList/index.tsx
  frontend/src/components/common/PageButtons/PageButtons.styled.ts
  frontend/src/components/common/PageButtons/index.tsx
  frontend/src/constants/pagination.ts
  frontend/src/contexts/PaginationContext.tsx
  frontend/src/hooks/__tests__/useMissions.test.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useDashboardDiscussion.ts
  frontend/src/hooks/useDashboardDiscussionComment.ts
  frontend/src/hooks/useDiscussions.ts
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/hooks/useMissions.ts
  frontend/src/hooks/useMyComments.ts
  frontend/src/hooks/usePagination.ts
  frontend/src/hooks/useSolutionSummaries.ts
  frontend/src/hooks/useSubmittedSolutions.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/DashboardPage/Discussion/index.tsx
  frontend/src/pages/DashboardPage/DiscussionComment/index.tsx
  frontend/src/pages/DashboardPage/MissionInProgress/index.tsx
  frontend/src/pages/DashboardPage/MyComments/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/SolutionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#700 상세 및 제출 페이지 웹 접근성 대응
  frontend/src/components/CommentSection/CommentList/CommentItem/index.tsx
  frontend/src/components/CommentSection/CommentList/CommentList.styled.ts
  frontend/src/components/CommentSection/CommentList/index.tsx
  frontend/src/components/CommentSection/index.tsx
  frontend/src/components/DiscussionDetail/DiscussionDetail.styled.ts
  frontend/src/components/DiscussionDetail/DiscussionDetailHeader.tsx
  frontend/src/components/DiscussionSubmit/DiscussionDescription.tsx
  frontend/src/components/DiscussionSubmit/DiscussionSubmit.styled.ts
  frontend/src/components/DiscussionSubmit/DiscussionTitle.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/Footer/Footer.styled.ts
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/MissionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/MissionSubmit/MissionThumbnail.tsx
  frontend/src/components/MissionSubmit/MissionTitle.styled.ts
  frontend/src/components/MissionSubmit/MissionTitle.tsx
  frontend/src/components/MissionSubmit/OneWord.styled.ts
  frontend/src/components/MissionSubmit/OneWord.tsx
  frontend/src/components/MissionSubmit/PRLink.styled.ts
  frontend/src/components/MissionSubmit/PRLink.tsx
  frontend/src/components/MissionSubmit/SubmitBanner.styled.ts
  frontend/src/components/MissionSubmit/SubmitBanner.tsx
  frontend/src/components/MissionSubmit/SubmitButton.styled.ts
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/SolutionDetail/SolutionDetailBottom.tsx
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/SolutionDetail/index.tsx
  frontend/src/components/common/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagList/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/SolutionDetailPage/index.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#704 웹 접근성 적용 (issue #699)
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionList/index.tsx
  frontend/src/components/MissionSubmit/SubmitBanner.tsx
  frontend/src/components/common/InfoCard/index.tsx
  frontend/src/pages/MissionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#706 랜딩 페이지 이미지 대체 및 헤더, 랜딩 웹 접근성 추가 (issue #697)
  frontend/src/assets/images/discussion.svg
  frontend/src/assets/images/levelMission.svg
  frontend/src/assets/images/rocket.svg
  frontend/src/assets/images/upArrow.svg
  frontend/src/assets/images/vscodeSolution.svg
  frontend/src/components/Header/index.tsx
  frontend/src/components/common/ScrollToTopButton/ScrollToTopButton.styled.ts
  frontend/src/hooks/useScrollComponent.ts
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
  frontend/src/pages/AboutPage/DiscussionSpace.tsx
  frontend/src/pages/AboutPage/LevelMission.tsx
  frontend/src/pages/AboutPage/Rocket.tsx
  frontend/src/pages/AboutPage/Solution.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/styles/mediaQueries.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#709 QA 개선 사항 반영 (issue #707)
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/UserProfile/UserProfile.styled.ts
  frontend/src/components/common/ScrollToTopButton/ScrollToTopButton.styled.ts
  frontend/src/components/common/ScrollToTopButton/index.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/hooks/useScrollVisibility.ts
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionListPage/DiscussionListPage.styled.ts
  frontend/src/pages/DiscussionSubmitPage/DiscussionSubmitPage.styled.ts
  frontend/src/pages/MissionDetailPage.styled.ts
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/MissionSubmitPage.styled.ts
  frontend/src/pages/SolutionDetailPage/SolutionDetailPage.styled.ts
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/utils/debounce.ts
Labels: 🎨 프론트엔드, 🚀 개선

#710 반응형 대응 (issue #703)
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/pages/DiscussionSubmitPage/DiscussionSubmitPage.styled.ts
  frontend/src/pages/MissionDetailPage.styled.ts
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/pages/MissionSubmitPage.styled.ts
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/SolutionDetailPage/SolutionDetailPage.styled.ts
  frontend/src/pages/SolutionDetailPage/index.tsx
  frontend/src/styles/GlobalLayout.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#708 대시보드 페이지 반응형 구현 (issue #705)
  frontend/src/components/DashBoard/DashboardDiscussion/DashboardDiscussion.styled.ts
  frontend/src/components/DashBoard/DashboardDiscussion/index.tsx
  frontend/src/components/DashBoard/DiscussionComment/index.tsx
  frontend/src/components/DashBoard/MyComments/MyCommentList.tsx
  frontend/src/components/DashBoard/MyComments/MyComments.styled.ts
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/styles/mediaQueries.ts
Labels: 🎨 프론트엔드, 🚀 개선

#711 헤더 반응형 구현 (issue #701)
  frontend/src/assets/images/hamburgerToggle.svg
  frontend/src/components/Header/Desktop.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/HeaderMenu.tsx
  frontend/src/components/Header/Mobile.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/styles/mediaQueries.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#713 QA 사항 반영 및 페이지네이션 버그 수정 (issue #712)
  frontend/src/components/SolutionList/index.tsx
  frontend/src/contexts/PaginationContext.tsx
  frontend/src/hooks/usePagination.ts
  frontend/src/pages/DiscussionListPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그, 🚀 개선

#718 리스트 반응형 적용 (issue #717)
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/SolutionList/SolutionList.styled.ts
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Card/Card.styled.ts
  frontend/src/pages/DiscussionListPage/DiscussionListPage.styled.ts
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/styles/GlobalLayout.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#721 본문으로 바로가기 버튼 안보이도록 수정 (issue #719)
  frontend/src/App.styled.ts
Labels: 🎨 프론트엔드, 🐛 버그

#716 디스커션 목록 조회 쿼리 개선 (issue #715)
  backend/src/main/java/develup/domain/discussion/DiscussionRepositoryCustom.java
  backend/src/main/resources/db/migration/V5__add_mission_id_index.sql
Labels: 🚛 백엔드, 🚀 개선

#725 푸터 반응형 수정 및 about 간격 조정
  frontend/src/App.styled.ts
  frontend/src/components/Footer/Footer.styled.ts
  frontend/src/pages/AboutPage/AboutPage.styled.ts
Labels: 🎨 프론트엔드, 🐛 버그

#726 페이지네이션 로직 버그 수정 (issue #723)
  frontend/src/apis/paginationAPI.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/DashBoard/SubmittedSolutions/index.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/components/SolutionList/index.tsx
  frontend/src/hooks/usePagination.ts
  frontend/src/hooks/useSubmitDiscussion.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/DashboardPage/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#727 미션 카드 크기 반응형 조정 (issue #724)
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/SolutionList/SolutionList.styled.ts
  frontend/src/components/SolutionList/index.tsx
  frontend/src/components/common/Card/Card.styled.ts
  frontend/src/components/common/InfoCard/InfoCard.styled.ts
Labels: 🎨 프론트엔드, 🚀 개선

#729 디스커션 및 솔루션 제출시 에러 수정 (issue #728)
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/hooks/useDiscussionTitle.ts
  frontend/src/hooks/useSolutionTitle.ts
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능

#733 반응형 디자인 수정 (issue #730)
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Card/Card.styled.ts
  frontend/src/components/common/TagList/TagList.styled.ts
  frontend/src/pages/MainPage/MainPage.styled.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#736 깃허브에서 이메일 수집하지 않도록 변경합니다. (issue #735)
  backend/src/main/java/develup/infra/auth/oauth/github/GithubOAuthStrategy.java
  backend/src/main/java/develup/infra/auth/oauth/github/dto/GithubUserInfoResponse.java
Labels: 🚛 백엔드, ⚒️ 기능

#734 디스커션 페이지네이션 적용 문제 해결 (issue #731)
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/DashBoard/DashboardDiscussion/DashboardDiscussion.styled.ts
  frontend/src/components/DashBoard/DashboardDiscussion/index.tsx
  frontend/src/components/DashBoard/DiscussionComment/index.tsx
  frontend/src/components/DashBoard/MyComments/MyCommentList.tsx
  frontend/src/components/DashBoard/SubmittedSolutions/index.tsx
  frontend/src/components/Mission/index.tsx
  frontend/src/components/common/PageButtons/PageButtons.styled.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useDashboardDiscussion.ts
  frontend/src/hooks/useDashboardDiscussionComment.ts
  frontend/src/hooks/useDiscussions.ts
  frontend/src/hooks/useMission.ts
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/hooks/useMyComments.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/hooks/useSubmittedSolutions.ts
  frontend/src/index.tsx
  frontend/src/pages/DashboardPage/DashBoardPageLayout/index.tsx
  frontend/src/pages/DashboardPage/MissionInProgress/index.tsx
  frontend/src/pages/DashboardPage/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/MissionDetailPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능

#740 대시보드 카드 줄바꿈 수정 (issue #739)
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/components/Mission/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/SubmittedSolutions.json
  frontend/src/mocks/missionInProgress.json
  frontend/src/mocks/missionWithStarted.json
  frontend/src/pages/MissionDetailPage.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능

#743 대시보드 카드 공통 컴포넌트로 추출 (issue #741)
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/index.tsx
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/DashboardPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그, ⚒️ 기능

#742 카드 컴포넌트 줄바꿈 수정 (issue #738)
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/SolutionDetail/SolutionDetailHeader.tsx
  frontend/src/components/common/InfoCard/InfoCard.styled.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#750 카드 정렬 및 디스커션 서스펜스 처리
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionList/index.tsx
  frontend/src/components/SolutionList/SolutionList.styled.ts
  frontend/src/components/SolutionList/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능
