Repository woowacourse-teams/2024-devel-up, pull requests merged in 2024-09, with the labels that each got.

#370 CORS 경로에 로컬 호스트 추가 (issue #366)
  backend/src/main/java/develup/api/config/WebConfig.java
Labels: 🚛 백엔드, 🐛 버그

#421 풀이 수정 기능 구현(issue #416)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/application/solution/UpdateSolutionRequest.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#420 풀이 댓글 수정 구현 (issue #419)
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
  backend/src/main/java/develup/application/solution/comment/UpdateSolutionCommentRequest.java
  backend/src/main/java/develup/application/solution/comment/UpdateSolutionCommentResponse.java
  backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentServiceTest.java
  backend/src/test/java/develup/domain/solution/comment/SolutionCommentTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#425 로그인 시 dev가 아닌 prod로 이어지도록 수정 (issue #424)
  frontend/src/components/Header/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#428 로그인 시 알맞은 주소로 리다이렉트하도록 수정
  frontend/src/components/Header/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#423 풀이 삭제 기능 구현(issue #422)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#430 디스커션 도메인 작성 (issue #426)
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTag.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTagId.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/test/java/develup/domain/discussion/DiscussionHashTagIdTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionHashTagTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionHashTagsTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionTest.java
  backend/src/test/java/develup/support/data/DiscussionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#434 Solution Service PR 검증 로직 개선(issue #433)
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/mission/MissionUrl.java
  backend/src/main/java/develup/domain/solution/PullRequestUrl.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
  backend/src/test/java/develup/domain/mission/MissionTest.java
  backend/src/test/java/develup/domain/mission/MissionUrlTest.java
  backend/src/test/java/develup/domain/solution/PullRequestUrlTest.java
  backend/src/test/java/develup/domain/solution/SolutionTest.java
  backend/src/test/java/develup/support/data/MissionTestData.java
  backend/src/test/java/develup/support/data/SolutionTestData.java
Labels: 🚛 백엔드, 🚀 개선

#436 제출된 솔루션만 수정 가능하도록 변경 (issue #435)
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/test/java/develup/domain/solution/SolutionTest.java
Labels: 🚛 백엔드, 🚀 개선

#438 디스커션 글쓰기 기능 구현 (issue #437)
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/discussion/CreateDiscussionRequest.java
  backend/src/main/java/develup/application/discussion/DiscussionResponse.java
  backend/src/main/java/develup/application/discussion/DiscussionService.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionHashTags.java
  backend/src/main/java/develup/domain/discussion/Title.java
  backend/src/main/java/develup/domain/hashtag/HashTagRepository.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
  backend/src/test/java/develup/application/discussion/DiscussionServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionTest.java
  backend/src/test/java/develup/support/data/DiscussionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#452 DiscussionDetail 페이지 구현 (issue #417)
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/DiscussionDetailPage/mock.json
Labels: 🎨 프론트엔드, ⚒️ 기능

#457 폰트 리소스 최적화 (issue #455)
  frontend/index.html
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/index.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/fonts.css
  frontend/webpack.common.js
Labels: 🎨 프론트엔드, 🚀 개선

#464 필요한 폰트만 불러오도록 하기 (issue #463)
  frontend/src/assets/fonts/Pretendard-Bold.woff2
  frontend/src/assets/fonts/Pretendard-Regular.woff2
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/styles/fonts.css
Labels: 🎨 프론트엔드, 🚀 개선

#466 폰트 외부 CDN 경로로 변경 (issue #465)
  frontend/src/assets/fonts/Pretendard-Bold.woff2
  frontend/src/assets/fonts/Pretendard-Regular.woff2
  frontend/src/styles/fonts.css
Labels: 🎨 프론트엔드, 🚀 개선

#450 디스커션 조회 기능 구현 (issue #442)
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/discussion/DiscussionResponse.java
  backend/src/main/java/develup/application/discussion/DiscussionService.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
  backend/src/test/java/develup/application/discussion/DiscussionServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#470 디스커션 리스트 구현 (issue #431)
  frontend/src/apis/discussionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/DiscussionListItem.tsx
  frontend/src/components/DiscussionList/discussionsMock.json
  frontend/src/components/DiscussionList/index.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useDiscussions.ts
  frontend/src/index.tsx
  frontend/src/pages/DiscussionListPage/DiscussionListPage.styled.ts
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#475 디스커션 제출 페이지 구현 (issue #432)
  frontend/src/apis/discussionAPI.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/DiscussionSubmit/DiscussionDescription.tsx
  frontend/src/components/DiscussionSubmit/DiscussionSubmit.style.ts
  frontend/src/components/DiscussionSubmit/DiscussionTitle.tsx
  frontend/src/components/DiscussionSubmit/index.tsx
  frontend/src/components/HashTagList/index.tsx
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/SolutionDetail/SolutionSection/SolutionDetailHeader.tsx
  frontend/src/components/common/HashTagButton/HashTagButton.styled.ts
  frontend/src/components/common/HashTagButton/index.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagList/TagList.styled.ts
  frontend/src/components/common/TagList/index.tsx
  frontend/src/components/common/TagMultipleList/TagMultipleList.styled.ts
  frontend/src/components/common/TagMultipleList/index.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/variants.ts
  frontend/src/hooks/useDescription.ts
  frontend/src/hooks/useDiscussionTitle.ts
  frontend/src/hooks/useSubmitDiscussion.ts
  frontend/src/hooks/useSubmitDiscussionMutation.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/index.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
  frontend/src/pages/DiscussionSubmitPage/DiscussionSubmitPage.style.ts
  frontend/src/pages/DiscussionSubmitPage/index.tsx
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/SolutionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#459 요청 및 응답 로깅 구현(issue #448)
  backend/src/main/java/develup/api/logging/LoggingFilter.java
  backend/src/main/resources/logback-spring.xml
Labels: 🚛 백엔드, ⚒️ 기능

#478 디스커션 댓글 기능 구현 (issue #418)
  frontend/src/apis/commentAPI.ts
  frontend/src/apis/discussionAPI.ts
  frontend/src/apis/discussionCommentAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutionCommentAPI.ts
  frontend/src/components/CommentSection/CommentForm/CommentForm.styled.ts
  frontend/src/components/CommentSection/CommentForm/index.tsx
  frontend/src/components/CommentSection/CommentForm/types.d.ts
  frontend/src/components/CommentSection/CommentList/CommentItem/CommentInfo.tsx
  frontend/src/components/CommentSection/CommentList/CommentItem/CommentReplyItem.tsx
  frontend/src/components/CommentSection/CommentList/CommentItem/CommentReplyList.tsx
  frontend/src/components/CommentSection/CommentList/CommentItem/CommentReplySection.tsx
  frontend/src/components/CommentSection/CommentList/CommentItem/index.tsx
  frontend/src/components/CommentSection/CommentList/CommentList.styled.ts
  frontend/src/components/CommentSection/CommentList/index.tsx
  frontend/src/components/CommentSection/CommentSection.styled.ts
  frontend/src/components/CommentSection/index.tsx
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/index.tsx
  frontend/src/components/SolutionDetail/CommentList/index.tsx
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useComments.ts
  frontend/src/hooks/useDiscussion.ts
  frontend/src/hooks/useDiscussionComments.ts
  frontend/src/hooks/useMyComments.ts
  frontend/src/hooks/usePostCommentMutation.ts
  frontend/src/hooks/usePostDiscussionCommentMutation.ts
  frontend/src/hooks/usePostSolutionCommentMutation.ts
  frontend/src/hooks/useSolutionComments.ts
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/DiscussionDetailPage/mock.json
  frontend/src/pages/SolutionDetailPage.tsx
  frontend/src/types/discussion.ts
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#460 Solution 단건 조회 n + 1 문제 해결(issue #453)
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, 🚀 개선

#485 디스커션 리스트 클릭 시 상세로 이동하는 버그 해결 (issue #483)
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/hooks/queries/keys.ts
Labels: 🎨 프론트엔드, 🐛 버그

#499 빌드 에러 해결 (issue #498)
  frontend/src/hooks/useMyComments.ts
Labels: 🎨 프론트엔드, 🐛 버그

#495 디스커션 디테일 페이지 태그가 두 개 보여지는 오류 해결 (issue #494)
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#488 디스커션 리스트 필터링 구현 (issue #487)
  frontend/src/components/DiscussionList/DiscussionListItem.tsx
  frontend/src/components/DiscussionList/index.tsx
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Badge/index.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagMultipleList/index.tsx
  frontend/src/constants/variants.ts
  frontend/src/pages/DiscussionListPage/DiscussionListPage.styled.ts
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/MissionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능, 🚀 개선

#502 디스커션 작성하기 버튼 추가 (issue #497)
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/DiscussionList/DiscussionListHeader.tsx
  frontend/src/components/DiscussionList/DiscussionListItem.tsx
  frontend/src/index.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/DiscussionListPage/DiscussionListPage.styled.ts
  frontend/src/pages/DiscussionListPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#480 무중단 배포 스크립트 작성 (issue #456)
  .github/workflows/backend_cd.yml
  backend/compose.yml
  backend/scripts/healthcheck.sh
  backend/src/main/java/develup/api/HealthApi.java
  backend/src/test/java/develup/api/HealthApiTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#507 개발서버 msw 환경 에러 픽스 (issue #506)
  frontend/src/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#511 fix: prod 프로파일 사용하도록 수정 (issue #510)
  backend/compose.yml
Labels: 🚛 백엔드, ⚒️ 기능

#521 msw 주석 해제 (issue #520)
  frontend/src/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#527 캐러셀 슬라이드에 커서 포인터 처리 (issue #523)
  frontend/src/components/Carousel/Carousel.styled.ts
Labels: 🎨 프론트엔드, 🚀 개선

#530 디스커션 QA 및 피드백 반영 (issue #529)
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/components/DiscussionList/DiscussionListHeader.tsx
  frontend/src/components/SolutionDetail/SolutionSection/SolutionSection.styled.ts
  frontend/src/components/SolutionDetail/SolutionSection/index.tsx
  frontend/src/components/common/TagButton/TagButton.styled.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/index.tsx
  frontend/src/pages/DiscussionDetailPage/DiscussionDetailHeader.tsx
  frontend/src/pages/DiscussionDetailPage/index.tsx
  frontend/src/pages/DiscussionListPage/index.tsx
  frontend/src/pages/DiscussionSubmitPage/index.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#526 Service Read/Write 분리 (issue #524)
  backend/src/main/java/develup/api/DiscussionApi.java
  backend/src/main/java/develup/api/DiscussionCommentApi.java
  backend/src/main/java/develup/api/HashTagApi.java
  backend/src/main/java/develup/api/MemberApi.java
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/api/auth/AuthArgumentResolver.java
  backend/src/main/java/develup/application/auth/oauth/OAuthService.java
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/DiscussionWriteService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentReadService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentService.java
  backend/src/main/java/develup/application/discussion/comment/DiscussionCommentWriteService.java
  backend/src/main/java/develup/application/hashtag/HashTagReadService.java
  backend/src/main/java/develup/application/member/MemberReadService.java
  backend/src/main/java/develup/application/member/MemberWriteService.java
  backend/src/main/java/develup/application/mission/MissionReadService.java
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/application/solution/SolutionWriteService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentReadService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentWriteService.java
  backend/src/test/java/develup/api/ApiTestSupport.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
  backend/src/test/java/develup/api/DiscussionCommentApiTest.java
  backend/src/test/java/develup/api/HashTagApiTest.java
  backend/src/test/java/develup/api/MemberApiTest.java
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
  backend/src/test/java/develup/application/discussion/DiscussionReadServiceTest.java
  backend/src/test/java/develup/application/discussion/DiscussionWriteServiceTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentReadServiceTest.java
  backend/src/test/java/develup/application/discussion/comment/DiscussionCommentWriteServiceTest.java
  backend/src/test/java/develup/application/member/MemberReadServiceTest.java
  backend/src/test/java/develup/application/member/MemberWriteServiceTest.java
  backend/src/test/java/develup/application/mission/MissionReadServiceTest.java
  backend/src/test/java/develup/application/solution/SolutionReadServiceTest.java
  backend/src/test/java/develup/application/solution/SolutionWriteServiceTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentReadServiceTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentWriteServiceTest.java
Labels: 🚛 백엔드, 🚀 개선

#534 status별 에러 핸들링 (issue #519)
  frontend/src/apis/clients/APIClient.ts
  frontend/src/apis/clients/httpMethod.ts
  frontend/src/apis/clients/throwAPIError.ts
  frontend/src/apis/error/HTTPError.ts
  frontend/src/components/common/Error/ErrorFallback.styled.ts
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/components/common/Error/QueryErrorBoundary.tsx
  frontend/src/components/common/PrivateRoute.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/404Page/NotFound.styled.ts
  frontend/src/pages/404Page/index.tsx
  frontend/src/pages/LoginPage/LoginPage.styled.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#540 대시보드에서 새로고침시 발생하는 에러를 해결 (issue #539)
  frontend/src/components/DashBoard/DashboardDiscussion/DiscussionItem.tsx
  frontend/src/components/DashBoard/SubmittedSolutions/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/DashboardPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#535 디스커션 목록 조회 시 댓글 수 100으로 고정되는 것 수정(issue #532)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/application/discussion/SummarizedDiscussionResponse.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentCount.java
  backend/src/main/java/develup/domain/discussion/comment/DiscussionCommentCounts.java
  backend/src/test/java/develup/api/DiscussionApiTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#537 로그 전송 주소 변경 (issue#536)
  backend/src/main/resources/logback-spring.xml
Labels: 🚛 백엔드, ⚒️ 기능

#547 readOnly 전파 문제 수정 (issue #545)
  backend/src/main/java/develup/api/auth/AuthArgumentResolver.java
Labels: 🚛 백엔드, 🐛 버그

#548 데벨업 v1.0.2 Release
  backend/src/main/java/develup/api/auth/AuthArgumentResolver.java
Labels: 🚛 백엔드, 🐛 버그

#550 대시보드에서 새로고침시 로그인 풀리는 문제 해결 (issue #549)
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/hooks/useUserInfo.ts
Labels: 🎨 프론트엔드, 🐛 버그

#554 삭제된 댓글은 댓글 수에 포함하지 않게 변경 (issue #551)
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
Labels: 🚛 백엔드, 🐛 버그

#553 https://devel-up.co.kr를 CORS 설정에 하드코딩(issue #552)
  backend/src/main/java/develup/api/config/WebConfig.java
Labels: 🚛 백엔드, 🐛 버그

#560 에러 발생시 홈으로 이동하도록 변경 (issue #559)
  backend/src/main/java/develup/api/.SubmissionApi.java.icloud
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/components/common/Error/QueryErrorBoundary.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#558 전체 디스커션 조회 시 미션, 해시태그 없으면 조회 안되는 문제 수정 (issue #555)
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/application/discussion/DiscussionReadServiceTest.java
Labels: 🚛 백엔드, 🐛 버그

#564 버튼 a 태그로 변경 (issue #563)
  frontend/src/components/common/Error/ErrorFallback.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#567 데벨업 v1.0.3 Release
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
  backend/src/main/java/develup/domain/discussion/DiscussionRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/application/discussion/DiscussionReadServiceTest.java
  backend/src/test/java/develup/domain/discussion/DiscussionRepositoryTest.java
  frontend/src/components/DiscussionList/DiscussionList.styled.ts
  frontend/src/components/DiscussionList/DiscussionListContent.tsx
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/components/common/Error/QueryErrorBoundary.tsx
  frontend/src/components/common/PrivateRoute.tsx
Labels: 🚛 백엔드, 🎨 프론트엔드, 🐛 버그, ⚒️ 기능, 🚀 개선

#570 미션 타이틀 공백으로 보내는 버그 수정 (issue #568)
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
Labels: 🚛 백엔드, 🐛 버그

#571 데벨업 v1.0.4 Release
  backend/src/main/java/develup/application/discussion/DiscussionReadService.java
  backend/src/main/java/develup/domain/discussion/Discussion.java
Labels: 🚛 백엔드, 🐛 버그

#572 에러 페이지 접속시 헤더 컴포넌트 없애기 (issue #569)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DiscussionList/DiscussionListItem.tsx
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/components/common/Error/ErrorLogo.tsx
  frontend/src/index.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#574 데벨업 v1.0.5 Release
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DiscussionList/DiscussionListItem.tsx
  frontend/src/components/common/Error/ErrorFallback.tsx
  frontend/src/components/common/Error/ErrorLogo.tsx
  frontend/src/index.tsx
Labels: 🚛 백엔드, 🎨 프론트엔드

#575 솔루션 목록 조회 쿼리 개선 (Issue #573)
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, 🚀 개선

#576 데벨업 v1.0.6 Release
  backend/src/main/java/develup/application/solution/SolutionReadService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, 🎨 프론트엔드
