Repository woowacourse-teams/2024-devel-up, pull requests merged in 2024-07, with the labels that each got.

#4 프론트엔드 초기 환경설정 (issue#3)
  frontend/.babelrc
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.nvmrc
  frontend/.prettierrc
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 프론트엔드, 기능

#9 스타일 초기 세팅(issue#5)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/header/header.styled.ts
  frontend/src/components/header/index.tsx
  frontend/src/styles/GlobalLayout.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 프론트엔드, 기능

#11 미션 리스트 조회 구현(issue#8)
  backend/src/main/java/develup/Application.java
  backend/src/main/java/develup/mission/Language.java
  backend/src/main/java/develup/mission/Mission.java
  backend/src/main/java/develup/mission/MissionApi.java
  backend/src/main/java/develup/mission/MissionRepository.java
  backend/src/main/java/develup/mission/MissionResponse.java
  backend/src/main/java/develup/mission/MissionService.java
  backend/src/main/java/develup/support/ApiResponse.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/ApplicationTests.java
Labels: 백엔드, 기능

#12 라우팅 초기 설정(issue#10)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/missionDetail/MissionDetail.tsx
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/webpack.common.js
Labels: 프론트엔드, 기능

#17 라우팅 초기 설정(issue#16)
  frontend/src/components/header/Header.styled.ts
  frontend/src/components/header/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/MissionDetailPage.tsx
Labels: 프론트엔드, 기능

#18 미션 제출 페이지 구현 (issue#13)
  frontend/src/App.tsx
  frontend/src/assets/images/githubLogo.svg
  frontend/src/components/missionSubmit/MissionSubmitForm.tsx
  frontend/src/components/missionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/missionSubmit/MissionThumbnail.tsx
  frontend/src/components/missionSubmit/OneWord.styled.ts
  frontend/src/components/missionSubmit/OneWord.tsx
  frontend/src/components/missionSubmit/PRLink.styled.ts
  frontend/src/components/missionSubmit/PRLink.tsx
  frontend/src/components/missionSubmit/SubmitBanner.styled.ts
  frontend/src/components/missionSubmit/SubmitBanner.tsx
  frontend/src/components/missionSubmit/SubmitButton.styled.ts
  frontend/src/components/missionSubmit/SubmitButton.tsx
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/MissionSubmitPage.styled.ts
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/types/svg.d.ts
Labels: 프론트엔드, 기능

#19 미션 리스트 페이지 구현 (issue#14)
  frontend/src/components/missionList/MissionItem.tsx
  frontend/src/components/missionList/MissionList.styled.ts
  frontend/src/components/missionList/missionMocks.ts
  frontend/src/index.tsx
  frontend/src/pages/MissionListPage.tsx
Labels: 프론트엔드, 기능

#22 미션 상세페이지 구현 (issue#15)
  frontend/src/components/missionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/missionDetailButtonGroup/index.tsx
  frontend/src/components/missionDetailContent/MissionDetailContent.styled.ts
  frontend/src/components/missionDetailContent/index.tsx
  frontend/src/components/missionDetailHeader/index.tsx
  frontend/src/components/missionDetailHeader/missionDetailHeader.styled.ts
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 프론트엔드, 기능

#23 미션 단건 조회 기능 구현(issue#20)
  backend/src/main/java/develup/mission/Mission.java
  backend/src/main/java/develup/mission/MissionApi.java
  backend/src/main/java/develup/mission/MissionService.java
  backend/src/test/java/develup/mission/MissionServiceTest.java
Labels: 백엔드, 기능

#26 미션 리스트 조회 테스트 구현 (issue#21)
  backend/src/test/java/develup/mission/MissionServiceTest.java
Labels: 백엔드, 기능

#27 미션 상세페이지 디자인 고도화 (issue#24)
  frontend/src/components/missionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/missionDetailButtonGroup/index.tsx
  frontend/src/components/missionDetailContent/MissionDetailContent.styled.ts
  frontend/src/components/missionDetailContent/index.tsx
  frontend/src/components/missionDetailHeader/index.tsx
  frontend/src/components/missionDetailHeader/missionDetailHeader.styled.ts
  frontend/src/pages/MissionDetailPage.styled.ts
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 프론트엔드, 기능

#28 시연을 위한 스타일 일관성 조정 (issue#25)
  frontend/src/assets/images/develupLogo.png
  frontend/src/components/header/Header.styled.ts
  frontend/src/components/header/index.tsx
  frontend/src/components/missionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/missionDetailButtonGroup/index.tsx
  frontend/src/components/missionDetailContent/MissionDetailContent.styled.ts
  frontend/src/components/missionDetailHeader/missionDetailHeader.styled.ts
  frontend/src/components/missionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/missionSubmit/OneWord.styled.ts
  frontend/src/components/missionSubmit/PRLink.styled.ts
  frontend/src/components/missionSubmit/SubmitButton.styled.ts
  frontend/src/pages/MissionListPage.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/types/global.d.ts
  frontend/webpack.common.js
Labels: 프론트엔드, 개선

#36 서버 URL 상수 파일을 생성합니다. (issue#35)
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/paths.ts
Labels: 프론트엔드, 기능

#37 JPA 엔티티 매핑 (issue#34)
  .idea/.gitignore
  .idea/2024-devel-up.iml
  .idea/aws.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/jpa.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sonarlint/issuestore/0/9/09ef49aa96aabeea0266b60de2c1b161a357660c
  .idea/sonarlint/issuestore/3/5/35a7c0bf0b93d685a994de9ac5c905e974dca0f0
  .idea/sonarlint/issuestore/3/9/392f7b8926835df0d74f30f6b78e417088d3bfc0
  .idea/sonarlint/issuestore/4/3/4314da7895e58be13e65bdf847258aa88c48bc08
  .idea/sonarlint/issuestore/7/c/7c6379149448166b9574c246760494b707df461e
  .idea/sonarlint/issuestore/9/0/905006035a05ab365d7a8d510a9c10826a715c10
  .idea/sonarlint/issuestore/d/0/d0ce0c91be0cfa9550d62d626a4b5c58adaa4dfd
  .idea/sonarlint/issuestore/d/8/d86a7ce5f35a101c8994577a915877e74defb650
  .idea/sonarlint/issuestore/f/8/f8bb43330ccf878492fef9d080d7a06611125f89
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/0/9/09ef49aa96aabeea0266b60de2c1b161a357660c
  .idea/sonarlint/securityhotspotstore/3/5/35a7c0bf0b93d685a994de9ac5c905e974dca0f0
  .idea/sonarlint/securityhotspotstore/3/9/392f7b8926835df0d74f30f6b78e417088d3bfc0
  .idea/sonarlint/securityhotspotstore/4/3/4314da7895e58be13e65bdf847258aa88c48bc08
  .idea/sonarlint/securityhotspotstore/7/c/7c6379149448166b9574c246760494b707df461e
  .idea/sonarlint/securityhotspotstore/9/0/905006035a05ab365d7a8d510a9c10826a715c10
  .idea/sonarlint/securityhotspotstore/d/0/d0ce0c91be0cfa9550d62d626a4b5c58adaa4dfd
  .idea/sonarlint/securityhotspotstore/d/8/d86a7ce5f35a101c8994577a915877e74defb650
  .idea/sonarlint/securityhotspotstore/f/8/f8bb43330ccf878492fef9d080d7a06611125f89
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  backend/src/main/java/develup/member/Member.java
  backend/src/main/java/develup/mission/Mission.java
  backend/src/main/java/develup/pair/Pair.java
  backend/src/main/java/develup/submission/Submission.java
  backend/src/main/resources/application.yml
Labels: 백엔드, 기능

#40 PR 템플릿에 RCA 룰 설명 작성 (issue#38)
  .github/pull_request_template.md
  .idea/sonarlint/issuestore/9/9/99d2d4406193bf0dc3e7b84a6c9b9109997a4864
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/9/9/99d2d4406193bf0dc3e7b84a6c9b9109997a4864
  .idea/sonarlint/securityhotspotstore/index.pb
Labels: 문서

#42 미션 description 컬럼 변경 (issue#41)
  backend/src/main/resources/data.sql
Labels: 백엔드, 기능

#44 ApiResponse를 제네릭으로 개선 (issue#43)
  backend/src/main/java/develup/mission/MissionApi.java
  backend/src/main/java/develup/support/ApiResponse.java
Labels: 백엔드, 개선

#50 미션 제출 기능 구현 (issue#29)
  backend/src/main/java/develup/member/Member.java
  backend/src/main/java/develup/mission/Language.java
  backend/src/main/java/develup/mission/MissionRepository.java
  backend/src/main/java/develup/submission/CreateSubmissionRequest.java
  backend/src/main/java/develup/submission/Submission.java
  backend/src/main/java/develup/submission/SubmissionApi.java
  backend/src/main/java/develup/submission/SubmissionRepository.java
  backend/src/main/java/develup/submission/SubmissionResponse.java
  backend/src/main/java/develup/submission/SubmissionService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/submission/SubmissionServiceTest.java
Labels: 백엔드, 기능

#51 미션 프로필 페이지 구현 (issue#39)
  frontend/src/apis/authAPI.ts
  frontend/src/components/header/Header.styled.ts
  frontend/src/components/missionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/missionDetailButtonGroup/index.tsx
  frontend/src/components/userProfile/UserProfile.styled.ts
  frontend/src/components/userProfile/UserProfileDescription.tsx
  frontend/src/components/userProfile/UserProfileEmail.tsx
  frontend/src/components/userProfile/UserProfileImage.tsx
  frontend/src/components/userProfile/UserProfileName.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/useUserInfo.ts
  frontend/src/index.tsx
  frontend/src/pages/MissionDetailPage.styled.ts
  frontend/src/pages/UserProfilePage.tsx
  frontend/src/types/index.ts
  frontend/tsconfig.json
Labels: 프론트엔드, 기능

#53 깃허브 인증 기능 (issue#32)
  backend/build.gradle
  backend/src/main/java/develup/Application.java
  backend/src/main/java/develup/auth/AuthApi.java
  backend/src/main/java/develup/auth/AuthService.java
  backend/src/main/java/develup/auth/GithubAccessTokenRequest.java
  backend/src/main/java/develup/auth/GithubAccessTokenResponse.java
  backend/src/main/java/develup/auth/GithubOAuthClient.java
  backend/src/main/java/develup/auth/GithubOAuthProperties.java
  backend/src/main/java/develup/auth/GithubOAuthService.java
  backend/src/main/java/develup/auth/JwtTokenProperties.java
  backend/src/main/java/develup/auth/JwtTokenProvider.java
  backend/src/main/java/develup/auth/SocialProfile.java
  backend/src/main/java/develup/auth/TokenProvider.java
  backend/src/main/java/develup/member/Member.java
  backend/src/main/java/develup/member/MemberRepository.java
  backend/src/main/java/develup/member/MemberResponse.java
  backend/src/main/java/develup/member/MemberService.java
  backend/src/main/java/develup/member/Provider.java
  backend/src/main/resources/application.yml
Labels: 백엔드, 기능

#60 CORS 프론트 개발 환경 추가(issue:#59)
  backend/src/main/java/develup/support/CorsConfig.java
Labels: 백엔드, 버그

#48 ci 초기 설정 추가 (issue#47)
  .github/workflows/ci.yml
  .github/workflows/teamMember.json
Labels: 백엔드, 기능

#69 CD 기능 구현 (Issue#68)
  .github/workflows/cd.yml
  .github/workflows/front_ci.yml
Labels: 백엔드, 기능

#72 프론트 ci 환경 구축 (issue#71)
  frontend/src/components/guide/HowToFork.tsx
  frontend/src/utils/__tests__/add.test.ts
  frontend/src/utils/add.ts
Labels: 프론트엔드, 기능

#63 리뷰 매칭 기능 구현(issue#33)
  backend/src/main/java/develup/member/Member.java
  backend/src/main/java/develup/pair/Pair.java
  backend/src/main/java/develup/submission/MyMission.java
  backend/src/main/java/develup/submission/MyMissionResponse.java
  backend/src/main/java/develup/submission/Pair.java
  backend/src/main/java/develup/submission/PairRepository.java
  backend/src/main/java/develup/submission/PairService.java
  backend/src/main/java/develup/submission/PairStatus.java
  backend/src/main/java/develup/submission/Submission.java
  backend/src/main/java/develup/submission/SubmissionApi.java
  backend/src/main/java/develup/submission/SubmissionRepository.java
  backend/src/main/java/develup/submission/SubmissionService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/ApplicationTests.java
  backend/src/test/java/develup/mission/MissionServiceTest.java
  backend/src/test/java/develup/pair/PairRepositoryTest.java
  backend/src/test/java/develup/submission/PairServiceTest.java
  backend/src/test/java/develup/submission/PairTest.java
  backend/src/test/java/develup/submission/SubmissionRepositoryTest.java
  backend/src/test/java/develup/submission/SubmissionServiceTest.java
  backend/src/test/java/develup/submission/SubmissionTest.java
  backend/src/test/resources/clean_data.sql
  backend/src/test/resources/mymissions.sql
Labels: 백엔드, 기능

#70 캐러셀 슬라이드 구현 (issue#57)
  frontend/src/components/carousel/Carousel.styled.ts
  frontend/src/components/carousel/Carousel.tsx
  frontend/src/hooks/useCarousel.ts
  frontend/src/pages/MissionListPage.tsx
Labels: 프론트엔드, 기능

#67 미션 현황 페이지 구현 (issue#49)
  frontend/src/components/myMission/myMissionCompleted/MyMissionCompleted.styled.ts
  frontend/src/components/myMission/myMissionCompleted/MyMissionCompleted.tsx
  frontend/src/components/myMission/myMissionInProgress/MyMissionInProgress.styled.ts
  frontend/src/components/myMission/myMissionInProgress/MyMissionInProgress.tsx
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/MyMissionPage.styled.ts
  frontend/src/pages/MyMissionPage.tsx
Labels: 프론트엔드, 기능

#58 Header 알림 기능 구현 (issue#45)
  frontend/.gitignore
  frontend/index.html
  frontend/src/assets/images/bell.svg
  frontend/src/components/common/ListenKeyDown.tsx
  frontend/src/components/header/Header.styled.ts
  frontend/src/components/header/index.tsx
  frontend/src/components/header/notiModal/NotiList.tsx
  frontend/src/components/header/notiModal/NotiModal.styled.ts
  frontend/src/components/header/notiModal/index.tsx
  frontend/src/components/header/notiModal/notiMocks.ts
  frontend/src/hooks/useClickOutside.ts
  frontend/src/index.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 프론트엔드, 기능

#78 최근 진행 중인 미션 단건 조회 기능 (issue #31)
  backend/src/main/java/develup/submission/MyMission.java
  backend/src/main/java/develup/submission/SubmissionApi.java
  backend/src/main/java/develup/submission/SubmissionRepository.java
  backend/src/main/java/develup/submission/SubmissionService.java
  backend/src/test/java/develup/submission/SubmissionServiceTest.java
  backend/src/test/resources/mymissions.sql
Labels: 백엔드, 기능

#83 스토리북 및 테스트 환경 설정 (issue #82)
  .github/workflows/front_storybook.yml
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/jest.config.ts
  frontend/jest.polyfills.js
  frontend/jest.setup.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/components/carousel/Carousel.tsx
  frontend/src/components/carousel/stories/Carousel.stories.tsx
  frontend/src/components/missionList/MissionItem.tsx
  frontend/src/hooks/__tests__/useMissions.test.tsx
  frontend/src/hooks/useMissions.ts
  frontend/src/hooks/useUserInfo.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missions.json
  frontend/src/mocks/server.ts
  frontend/src/pages/MissionListPage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#80 제출 성공시 팝업 구현 (issue #73)
  frontend/.gitignore
  frontend/index.html
  frontend/src/components/PopUp/SuccessMissionSubmitPopUp.styled.ts
  frontend/src/components/PopUp/SuccessMissionSubmitPopUp.tsx
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/ModalBackdrop.tsx
  frontend/src/components/common/Modal/ModalContainer.tsx
  frontend/src/components/common/Modal/ModalPortal.tsx
  frontend/src/components/common/Modal/ModalProvider.tsx
  frontend/src/components/common/Modal/ScrollPreventer.tsx
  frontend/src/contexts/ModalContext.ts
  frontend/src/hooks/useAnimation.ts
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#89 CI CD 파이프라인이 눈에 잘 보이도록 스크립트 개선(Issue #88)
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/front_ci.yml
Labels: 🚛 백엔드, 🎨 프론트엔드, 🚀 개선

#87 컴포넌트 관련 폴더명 첫글자를 대문자로 변경 (issue #85)
  frontend/src/App.tsx
  frontend/src/components/Carousel/Carousel.styled.ts
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/Guide/HowToFork.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/NotiModal/NotiList.tsx
  frontend/src/components/Header/NotiModal/NotiModal.styled.ts
  frontend/src/components/Header/NotiModal/index.tsx
  frontend/src/components/Header/NotiModal/notiMocks.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/MissionDetailButtonGroup/index.tsx
  frontend/src/components/MissionDetailContent/MissionDetailContent.styled.ts
  frontend/src/components/MissionDetailContent/index.tsx
  frontend/src/components/MissionDetailHeader/index.tsx
  frontend/src/components/MissionDetailHeader/missionDetailHeader.styled.ts
  frontend/src/components/MissionList/MissionItem.tsx
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionList/missionMocks.ts
  frontend/src/components/MissionSubmit/MissionSubmitForm.tsx
  frontend/src/components/MissionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/MissionSubmit/MissionThumbnail.tsx
  frontend/src/components/MissionSubmit/OneWord.styled.ts
  frontend/src/components/MissionSubmit/OneWord.tsx
  frontend/src/components/MissionSubmit/PRLink.styled.ts
  frontend/src/components/MissionSubmit/PRLink.tsx
  frontend/src/components/MissionSubmit/SubmitBanner.styled.ts
  frontend/src/components/MissionSubmit/SubmitBanner.tsx
  frontend/src/components/MissionSubmit/SubmitButton.styled.ts
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.styled.ts
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.tsx
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.styled.ts
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.tsx
  frontend/src/components/Tab/Tab.styled.ts
  frontend/src/components/Tab/TabCurrentContent.tsx
  frontend/src/components/Tab/TabHeader.tsx
  frontend/src/components/Tab/TabListWrapper.tsx
  frontend/src/components/Tab/Tabs.tsx
  frontend/src/components/UserProfile/UserProfile.styled.ts
  frontend/src/components/UserProfile/UserProfileDescription.tsx
  frontend/src/components/UserProfile/UserProfileEmail.tsx
  frontend/src/components/UserProfile/UserProfileImage.tsx
  frontend/src/components/UserProfile/UserProfileName.tsx
  frontend/src/pages/GuidePage.tsx
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/pages/MissionListPage.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/MyMissionPage.tsx
  frontend/src/pages/UserProfilePage.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#86 Swagger 초기 설정 (issue #81)
  .gitignore
  backend/build.gradle
  backend/src/main/java/develup/support/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: 🚛 백엔드, ⚒️ 기능

#103 BE CD 배포 스크립트 작성
  .github/workflows/cd.yml
Labels: 🚛 백엔드, ⚒️ 기능

#106 BE CD 배포 스크립트 수정 (issue #105)
  .github/workflows/cd.yml
Labels: 🚛 백엔드, ⚒️ 기능

#109 커스텀 예외 및 전역 예외 핸들러 작성 (issue #102)
  backend/src/main/java/develup/support/config/CorsConfig.java
  backend/src/main/java/develup/support/config/SwaggerConfig.java
  backend/src/main/java/develup/support/exception/DevelupException.java
  backend/src/main/java/develup/support/exception/ExceptionDetail.java
  backend/src/main/java/develup/support/exception/ExceptionResponse.java
  backend/src/main/java/develup/support/exception/ExceptionType.java
  backend/src/main/java/develup/support/exception/GlobalExceptionHandler.java
  backend/src/test/java/develup/support/exception/GlobalExceptionHandlerTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#115 공통 컴포넌트 프로퍼티 대소문자 수정 (issue #114)
  frontend/src/components/MissionSubmit/PRLink.tsx
  frontend/src/components/common/Input/stories/Input.stories.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#118 프론트엔드 배포 환경 CORS 설정에 추가(Issue #117)
  backend/src/main/java/develup/api/config/WebConfig.java
Labels: 🚛 백엔드, 🐛 버그

#104 공통 컴포넌트 구현 (버튼, 진행 중인 미션 배너) (issue #94)
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.styled.ts
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.tsx
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompletedCard.tsx
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.styled.ts
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.tsx
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgressBanner.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/pages/MyMissionPage.styled.ts
  frontend/src/pages/MyMissionPage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#120 백엔드 URL 연결 (issue #119)
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, 🚀 개선

#122 프론트엔드 배포 환경 CORS 설정 오타 수정(Issue #121)
  backend/src/main/java/develup/api/config/WebConfig.java
Labels: 🚛 백엔드, 🐛 버그

#116 테스트 코드 개선(issue #65)
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/submission/PairService.java
  backend/src/main/java/develup/application/submission/SubmissionService.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/submission/Pair.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/application/submission/PairServiceTest.java
  backend/src/test/java/develup/application/submission/SubmissionServiceTest.java
  backend/src/test/java/develup/domain/pair/PairRepositoryTest.java
  backend/src/test/java/develup/domain/submission/PairTest.java
  backend/src/test/java/develup/domain/submission/SubmissionRepositoryTest.java
  backend/src/test/java/develup/domain/submission/SubmissionTest.java
  backend/src/test/java/develup/support/IntegrationTestSupport.java
  backend/src/test/java/develup/support/cleaner/DatabaseCleaner.java
  backend/src/test/java/develup/support/cleaner/DatabaseClearExtension.java
  backend/src/test/java/develup/support/data/MemberTestData.java
  backend/src/test/java/develup/support/data/MissionTestData.java
  backend/src/test/java/develup/support/data/SubmissionTestData.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/clean_data.sql
  backend/src/test/resources/mymissions.sql
Labels: 🚛 백엔드, 🚀 개선

#113 BE CD 구조화 및 리팩토링 (issue #107)
  .github/workflows/cd.yml
Labels: 🚛 백엔드, 🚀 개선

#125 백엔드 cd 파일명 변경
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, 🚀 개선

#129 백로그 이슈 템플릿 추가 (issue #128)
  .github/ISSUE_TEMPLATE/backlog.md
Labels: 📋 문서

#131 이슈 템플릿 레이블 수정 (issue #130)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/improvement.md
Labels: 📋 문서

#133 이미지 경로 변경 (issue #132)
  backend/src/main/resources/data.sql
  backend/src/test/resources/mymissions.sql
Labels: 🚛 백엔드, 🚀 개선

#111 CI 스크립트 개선 (issue #108)
  .github/workflows/backend_ci.yml
  .github/workflows/front_ci.yml
  .github/workflows/teamMember.json
Labels: 🚛 백엔드, 🚀 개선

#136 백엔드 CD Push시 커밋 메시지, 링크를 슬랙 메시지로 전송할 수 있도록 개선 (issue #134)
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, 🚀 개선

#127 인가 코드 작성 (issue #99)
  backend/src/main/java/develup/api/AuthApi.java
  backend/src/main/java/develup/api/MemberApi.java
  backend/src/main/java/develup/api/auth/Auth.java
  backend/src/main/java/develup/api/auth/AuthArgumentResolver.java
  backend/src/main/java/develup/api/auth/CookieAuthorizationExtractor.java
  backend/src/main/java/develup/api/common/CookieUtils.java
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/auth/Accessor.java
  backend/src/main/java/develup/application/auth/AuthService.java
  backend/src/main/java/develup/application/auth/OAuthUserInfo.java
  backend/src/main/java/develup/application/member/MemberService.java
  backend/src/main/java/develup/infra/auth/GithubAccessTokenRequest.java
  backend/src/main/java/develup/infra/auth/GithubAccessTokenResponse.java
  backend/src/main/java/develup/infra/auth/JwtTokenProvider.java
  backend/src/main/java/develup/infra/auth/github/GithubAccessTokenRequest.java
  backend/src/main/java/develup/infra/auth/github/GithubAccessTokenResponse.java
  backend/src/main/java/develup/infra/auth/github/GithubOAuthClient.java
  backend/src/main/java/develup/infra/auth/github/GithubOAuthProperties.java
  backend/src/main/java/develup/infra/auth/github/GithubOAuthProvider.java
  backend/src/main/java/develup/infra/auth/github/GithubUserInfo.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/AuthApiTest.java
  backend/src/test/java/develup/api/MemberApiTest.java
  backend/src/test/java/develup/api/auth/CookieAuthorizationExtractorTest.java
  backend/src/test/java/develup/api/exception/GlobalExceptionHandlerTest.java
  backend/src/test/java/develup/application/member/MemberServiceTest.java
  backend/src/test/java/develup/infra/auth/JwtTokenProviderTest.java
  backend/src/test/java/develup/support/IntegrationTestSupport.java
  backend/src/test/resources/application.yml
Labels: 🚛 백엔드, ⚒️ 기능, 🚀 개선

#139 Front CI 슬랙 메시지 전송 로직 수정 (issue #138)
  .github/workflows/front_ci.yml
Labels: 🎨 프론트엔드, 🐛 버그

#137 미션 상세 페이지 디자인 및 데이터 연결 구현 (issue #55)
  frontend/src/apis/missionAPI.ts
  frontend/src/assets/images/infoIcon.svg
  frontend/src/assets/images/java.svg
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/MissionDetailButtonGroup/MissionDetailButtonGroup.styled.ts
  frontend/src/components/MissionDetailButtonGroup/index.tsx
  frontend/src/components/MissionDetailContent/MissionDetailContent.styled.ts
  frontend/src/components/MissionDetailHeader/index.tsx
  frontend/src/components/MissionDetailHeader/missionDetailHeader.styled.ts
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/MissionDetailPage.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#143 커밋 메시지 상단 한 줄만 사용하도록 수정 (issue #142)
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, 🐛 버그

#135 리뷰 완료 기능 추가(Issue #66)
  backend/src/main/java/develup/api/PairApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/submission/PairService.java
  backend/src/main/java/develup/domain/submission/Pair.java
  backend/src/main/java/develup/domain/submission/PairRepository.java
  backend/src/main/java/develup/domain/submission/PairStatus.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/application/submission/PairServiceTest.java
  backend/src/test/java/develup/domain/submission/PairRepositoryTest.java
  backend/src/test/java/develup/domain/submission/PairTest.java
  backend/src/test/java/develup/support/data/PairTestData.java
  backend/src/test/resources/mymissions.sql
Labels: 🚛 백엔드, ⚒️ 기능

#147 infoIcon 경로명 수정 (issue #146)
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
Labels: 🎨 프론트엔드, 🐛 버그

#144 폰트 설정 (issue #141)
  frontend/index.html
  frontend/src/styles/GlobalStyle.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#152 각 페이지 API 연결 및 고도화 (issue #126)
  frontend/src/apis/missionAPI.ts
  frontend/src/assets/images/leftArrow.svg
  frontend/src/assets/images/rightArrow.svg
  frontend/src/components/Carousel/Carousel.styled.ts
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/MissionSubmit/OneWord.tsx
  frontend/src/components/MissionSubmit/PRLink.tsx
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/components/common/LoadingSpinner/LoadingSpinner.styled.ts
  frontend/src/components/common/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/constants/messages.ts
  frontend/src/constants/regex.ts
  frontend/src/hooks/__tests__/useSubmissionMutation.test.tsx
  frontend/src/hooks/useCarousel.ts
  frontend/src/hooks/useComment.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useSubmission.ts
  frontend/src/hooks/useSubmissionMutation.ts
  frontend/src/hooks/useUrl.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/submission.json
  frontend/src/pages/MissionListPage.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/types/index.ts
  frontend/src/utils/validate.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#150 메인 페이지 스타일링 고도화 (issue #123)
  frontend/index.html
  frontend/src/components/Header/NotiModal/NotiList.tsx
  frontend/src/components/Header/NotiModal/NotiModal.styled.ts
  frontend/src/components/Header/NotiModal/index.tsx
  frontend/src/components/Header/NotiModal/notiMocks.ts
  frontend/src/components/MissionList/MissionItem.tsx
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/Tab/Tab.styled.ts
  frontend/src/components/Tab/TabHeader.tsx
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Badge/index.tsx
  frontend/src/components/common/Card/Card.styled.ts
  frontend/src/pages/MissionListPage.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#154 깃허브 OAuth 관련 환경변수 등록 (issue #153)
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, ⚒️ 기능

#151 백엔드 인가 적용(issue #140)
  backend/src/main/java/develup/api/AuthApi.java
  backend/src/main/java/develup/api/MemberApi.java
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/PairApi.java
  backend/src/main/java/develup/api/SubmissionApi.java
  backend/src/main/java/develup/api/auth/Auth.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/mission/MissionResponse.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/submission/SubmissionService.java
  backend/src/main/java/develup/domain/submission/SubmissionRepository.java
  backend/src/test/java/develup/application/member/MemberServiceTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/application/submission/SubmissionServiceTest.java
  backend/src/test/java/develup/domain/submission/SubmissionRepositoryTest.java
  backend/src/test/java/develup/infra/auth/JwtTokenProviderTest.java
Labels: 🚛 백엔드, ⚒️ 기능, 🚀 개선

#164 application-dev.yml, application-local.yml 분리 (Issue #163)
  .github/workflows/backend_cd.yml
  backend/src/main/resources/application-common.yml
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: 🚛 백엔드, ⚒️ 기능

#165 application-dev.yml, application-local.yml 분리 (Issue #163)
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, 🐛 버그

#159 미션 현황 데이터 연결 및 디자인 (issue #148)
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.styled.ts
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompleted.tsx
  frontend/src/components/MyMission/MyMissionCompleted/MyMissionCompletedCard.tsx
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.styled.ts
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgress.tsx
  frontend/src/components/MyMission/MyMissionInProgress/MyMissionInProgressBanner.tsx
  frontend/src/components/Submission/Submission.styled.ts
  frontend/src/components/Submission/SubmissionCompleted.tsx
  frontend/src/components/Submission/SubmissionCompletedCard.tsx
  frontend/src/components/Submission/SubmissionInProgress.tsx
  frontend/src/components/Submission/SubmissionInProgressBanner.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useCompleteReview.ts
  frontend/src/hooks/useMissionCompleted.ts
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/index.tsx
  frontend/src/pages/MissionListPage.tsx
  frontend/src/pages/MyMissionPage.tsx
  frontend/src/pages/SubmissionPage.styled.ts
  frontend/src/pages/SubmissionPage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#167 로그인 구현 (issue #62)
  frontend/src/apis/authAPI.ts
  frontend/src/apis/clients/APIClient.ts
  frontend/src/apis/paths.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/UserProfile/UserProfileImage.tsx
  frontend/src/components/common/PrivateRoute.tsx
  frontend/src/hooks/useUserInfo.ts
  frontend/src/pages/MissionListPage.tsx
  frontend/src/pages/UserProfilePage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#166 CI 와 브랜치 보호 설정이 충돌하는 경우 해결
  .github/workflows/backend_ci.yml
  .github/workflows/front_ci.yml
Labels: 🚛 백엔드, 🚀 개선

#161 스타일 고도화 (issue #160)
  frontend/src/apis/clients/APIClient.ts
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/MissionSubmit/MissionSubmitForm.tsx
  frontend/src/components/MissionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/MissionSubmit/MissionThumbnail.tsx
  frontend/src/components/MissionSubmit/OneWord.tsx
  frontend/src/components/MissionSubmit/PRLink.styled.ts
  frontend/src/components/Tab/Tab.styled.ts
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/TextArea/TextArea.styled.ts
  frontend/src/constants/regex.ts
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/styles/GlobalStyle.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#172 데모 전 버그 해결 (issue #169)
  frontend/src/apis/baseUrl.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Submission/SubmissionInProgress.tsx
  frontend/src/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#177 미션 진행과 관련한 컨텐츠 임시 생성 (issue #176)
  frontend/src/apis/clients/APIClient.ts
  frontend/src/components/Guide/HowToFork.tsx
  frontend/src/components/Guide/HowToPr.tsx
  frontend/src/components/Guide/HowToReview.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionList/MissionItem.tsx
  frontend/src/pages/GuidePage.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#158 리뷰 완료 기능 관련 추가 리뷰 반영 (Issue #157)
  backend/src/main/java/develup/api/PairApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/submission/PairService.java
  backend/src/main/java/develup/domain/submission/Pair.java
  backend/src/test/java/develup/application/submission/PairServiceTest.java
  backend/src/test/java/develup/domain/submission/PairTest.java
  backend/src/test/resources/mymissions.sql
Labels: 🚛 백엔드, 🚀 개선
