Repository woowacourse-teams/2024-devel-up, pull requests merged in 2024-08, with the labels that each got.

#188 이건 무효야(issue #187)
  backend/src/main/java/develup/api/MemberApi.java
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/PairApi.java
  backend/src/main/java/develup/api/SubmissionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/mission/MissionResponse.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/submission/CreateSubmissionRequest.java
  backend/src/main/java/develup/application/submission/MyMissionResponse.java
  backend/src/main/java/develup/application/submission/PairService.java
  backend/src/main/java/develup/application/submission/SubmissionResponse.java
  backend/src/main/java/develup/application/submission/SubmissionService.java
  backend/src/main/java/develup/domain/mission/Language.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/submission/MyMission.java
  backend/src/main/java/develup/domain/submission/Pair.java
  backend/src/main/java/develup/domain/submission/PairRepository.java
  backend/src/main/java/develup/domain/submission/PairStatus.java
  backend/src/main/java/develup/domain/submission/Submission.java
  backend/src/main/java/develup/domain/submission/SubmissionRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MemberApiTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/application/submission/PairServiceTest.java
  backend/src/test/java/develup/application/submission/SubmissionServiceTest.java
  backend/src/test/java/develup/domain/submission/PairRepositoryTest.java
  backend/src/test/java/develup/domain/submission/PairTest.java
  backend/src/test/java/develup/domain/submission/SubmissionRepositoryTest.java
  backend/src/test/java/develup/domain/submission/SubmissionTest.java
  backend/src/test/java/develup/support/data/MissionTestData.java
  backend/src/test/java/develup/support/data/PairTestData.java
  backend/src/test/java/develup/support/data/SubmissionTestData.java
  backend/src/test/resources/mymissions.sql
Labels: 🚛 백엔드, 🚀 개선

#192 미션, 솔루션 엔티티 생성(issue #190)
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionStatus.java
  backend/src/test/java/develup/support/data/MissionTestData.java
  backend/src/test/java/develup/support/data/SolutionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#198 모니터링을 위한 매트릭 제공 엔드포인트 추가
  backend/build.gradle
  backend/src/main/resources/application-common.yml
Labels: 🚛 백엔드, ⚒️ 기능

#199 미션 목록 조회 구현 (issue #197)
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/application/mission/MissionResponse.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/domain/mission/MissionTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#203 feat: 톰캣의 mBean 레지스트리 활성화 (Issue #202)
  backend/src/main/resources/application-common.yml
Labels: 🚛 백엔드, 🐛 버그

#205 2차 데모데이 롤백(Issue #204)
  .github/workflows/backend_cd.yml
  backend/src/main/java/develup/api/common/CookieUtils.java
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/resources/application-dev.yml
Labels: 🚛 백엔드, 🎨 프론트엔드, 🐛 버그

#206 미션 목록 조회 구현 (issue #200)
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/mission/MissionWithStartedResponse.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#208 멤버 API 테스트 응답 보완 (issue #207)
  backend/src/test/java/develup/api/MemberApiTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#209 솔루션 리스트 조회 기능 구현 (issue #196)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionSummary.java
  backend/src/main/resources/data.sql
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/useSolutions.ts
  frontend/src/index.tsx
  frontend/src/pages/SolutionListPage.tsx
Labels: 🚛 백엔드, 🎨 프론트엔드, ⚒️ 기능

#213 CI 스크립트에서 슬랙 아이디 제거(Issue #212)
  .github/workflows/backend_ci.yml
  .github/workflows/front_ci.yml
Labels: 🚛 백엔드, 🎨 프론트엔드, 🐛 버그

#214 CI 스크립트 오타 제거(Issue #212)
  .github/workflows/backend_ci.yml
  .github/workflows/front_ci.yml
Labels: 🚛 백엔드, 🎨 프론트엔드, 🐛 버그

#216 SameSite 쿠키 이슈 해결(Issue #215)
  .github/workflows/backend_cd.yml
  backend/src/main/java/develup/api/common/CookieUtils.java
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/resources/application-dev.yml
Labels: 🚛 백엔드, 🐛 버그

#210 Sentry 초기 설정 (Issue #201)
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/clients/APIClient.ts
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/webpack.common.js
Labels: 🎨 프론트엔드, ⚒️ 기능

#218 로키 설정 (issue #217)
  backend/build.gradle
  backend/src/main/resources/logback-spring.xml
Labels: 🚛 백엔드, ⚒️ 기능

#221 데벨업 소개서 추가 (issue #219)
  README.md
Labels: 📋 문서

#225 GA4 세팅 (Issue #222)
  frontend/index.html
Labels: 🎨 프론트엔드, ⚒️ 기능

#223 솔루션 단건 조회 기능 구현(issue #211)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
  backend/src/test/java/develup/domain/mission/MissionTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#230 전역 예외 로그 레벨 개선 (issue #228)
  backend/src/main/java/develup/api/exception/GlobalExceptionHandler.java
  backend/src/main/resources/logback-spring.xml
Labels: 🚛 백엔드, 🚀 개선

#232 스프링 쿠키로 변경 (issue #231)
  backend/src/main/java/develup/api/common/CookieUtils.java
Labels: 🚛 백엔드, 🚀 개선

#233 미션 시작 기능 구현(issue #227)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/StartSolutionRequest.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionStatus.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#236 Solution 리스트 페이지 리팩토링 및 스타일링 보완 (issue #224)
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/HeaderMenu.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionList/MissionItem.tsx
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionList/index.tsx
  frontend/src/components/common/InfoCard/InfoCard.styled.ts
  frontend/src/components/common/InfoCard/index.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/useSolutions.ts
  frontend/src/index.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MissionListPage.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/SolutionListPage.tsx
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/pages/SolutionListPage/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#238 변경된 API 스펙 반영 (issue #235)
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/types/solution.ts
Labels: 🎨 프론트엔드, 🚀 개선

#237 미션 제출 기능 구현 (issue #220)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/common/CookieUtils.java
  backend/src/main/java/develup/api/config/WebConfig.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionRequest.java
  backend/src/main/java/develup/application/solution/SolutionResponse.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/application/solution/SolutionSubmit.java
  backend/src/main/java/develup/domain/mission/MissionRepositoryName.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/Title.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
  backend/src/test/java/develup/infra/auth/JwtTokenProviderTest.java
  backend/src/test/java/develup/support/data/SolutionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#241 프론트엔드 CD 스크립트 작성 (Issue #229)
  .github/workflows/front_cd.yml
Labels: 🎨 프론트엔드, ⚒️ 기능

#245 data.sql 오류로 인한 build 에러 수정
  backend/src/main/resources/data.sql
Labels: 🚛 백엔드, 🐛 버그

#248 미션 상세 페이지에서 분기처리 수정 (issue #247)
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/hooks/useSubmitSolutionMutation.ts
Labels: 🎨 프론트엔드, 🚀 개선

#250 새로고침 에러 수정 (issue #249)
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/hooks/useSubmitSolutionMutation.ts
Labels: 🎨 프론트엔드, 🚀 개선

#257 transactional 어노테이션 추가 (issue #255)
  backend/src/main/java/develup/application/solution/SolutionService.java
Labels: 🚛 백엔드, 🐛 버그

#271 @WebMvcTest로 전환(issue #270)
  backend/src/test/java/develup/api/ApiTestSupport.java
  backend/src/test/java/develup/api/AuthApiTest.java
  backend/src/test/java/develup/api/MemberApiTest.java
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/api/exception/GlobalExceptionHandlerTest.java
Labels: 🚛 백엔드, 🚀 개선

#277 미션 상세 페이지 하드코딩된 내용을 실제 데이터로 대체 (issue: #240)
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/utils/populateMissionDescription.ts
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/MissionList/index.tsx
  frontend/src/components/common/InfoCard/index.tsx
  frontend/src/hooks/useMissions.ts
  frontend/src/mocks/missions.json
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#276 미션에 짧은 한줄 소개가 없는 오류 수정 (Issue #274)
  backend/src/main/java/develup/application/mission/MissionResponse.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/support/data/MissionTestData.java
Labels: 🚛 백엔드, 🐛 버그

#284 MissionResponse, Mission을 각각 Mission, MissionWithDescription으로 수정
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/utils/populateMissionDescription.ts
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/MissionList/index.tsx
  frontend/src/hooks/useMission.ts
  frontend/src/hooks/useMissions.ts
  frontend/src/types/index.ts
Labels: 🚀 개선

#267 미션 제출 기능 리팩터링 (issue #266)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/StartSolutionRequest.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/SolutionRequest.java
  backend/src/main/java/develup/application/solution/SolutionResponse.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/application/solution/StartSolutionRequest.java
  backend/src/main/java/develup/application/solution/SubmitSolutionRequest.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/mission/MissionRepositoryName.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionSubmit.java
  backend/src/main/java/develup/domain/solution/Title.java
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
  backend/src/test/java/develup/domain/solution/SolutionTest.java
  backend/src/test/java/develup/support/data/MissionTestData.java
Labels: 🚛 백엔드, 🚀 개선

#295 테스트 실패시에도 성공이라 메세지 보내는 현상 수정 (Issue #294)
  .github/workflows/backend_ci.yml
Labels: 🚛 백엔드, 🐛 버그

#300 깃허브 로그인 플로우를 개선 (Issue #298)
  backend/src/main/java/develup/application/auth/OAuthUserInfo.java
  backend/src/main/java/develup/infra/auth/github/GithubUserInfo.java
Labels: 🚛 백엔드, 🚀 개선

#293 내가 제출한 솔루션 리스트 조회 기능 구현 (issue #288)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/application/solution/MySolutionResponse.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/solution/SolutionServiceTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#292 솔루션 댓글 API 구현 (issue #269)
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/solution/comment/CommentGroupingService.java
  backend/src/main/java/develup/application/solution/comment/CreateSolutionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentRepliesResponse.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentRequest.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
  backend/src/main/java/develup/application/solution/comment/SolutionReplyResponse.java
  backend/src/main/java/develup/domain/CreatedAtAuditableEntity.java
  backend/src/main/java/develup/domain/IdentifiableEntity.java
  backend/src/main/java/develup/domain/solution/comment/SolutionComment.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
  backend/src/main/java/develup/infra/jpa/JpaAuditingConfig.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/ApiTestSupport.java
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
  backend/src/test/java/develup/application/solution/comment/CommentGroupingServiceTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentRepliesResponseTest.java
  backend/src/test/java/develup/application/solution/comment/SolutionCommentServiceTest.java
  backend/src/test/java/develup/domain/solution/comment/SolutionCommentTest.java
  backend/src/test/java/develup/support/data/SolutionCommentTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#296 해시태깅 기능 구현(issue #273)
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/api/exception/ExceptionType.java
  backend/src/main/java/develup/application/hashtag/HashTagResponse.java
  backend/src/main/java/develup/application/mission/MissionResponse.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/mission/MissionWithStartedResponse.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/application/solution/SummarizedSolutionResponse.java
  backend/src/main/java/develup/domain/hashtag/HashTag.java
  backend/src/main/java/develup/domain/hashtag/HashTagRepository.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionHashTag.java
  backend/src/main/java/develup/domain/mission/MissionHashTags.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionSummary.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/domain/mission/MissionHashTagsTest.java
  backend/src/test/java/develup/domain/mission/MissionRepositoryTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
  backend/src/test/java/develup/support/data/HashTagTestData.java
  backend/src/test/java/develup/support/data/MissionTestData.java
Labels: 🚛 백엔드, ⚒️ 기능

#286 버튼 컴포넌트 수정 (Issue #179)
  frontend/src/apis/missionAPI.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionSubmit/SubmitBanner.styled.ts
  frontend/src/components/ModalContent/MissionProcess/ModalProcess.styled.ts
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/components/Submission/Submission.styled.ts
  frontend/src/components/Submission/SubmissionCompleted.tsx
  frontend/src/components/Submission/SubmissionCompletedCard.tsx
  frontend/src/components/Submission/SubmissionInProgress.tsx
  frontend/src/components/Submission/SubmissionInProgressBanner.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/variants.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useCompleteReview.ts
  frontend/src/hooks/useMissionCompleted.ts
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/index.tsx
  frontend/src/pages/SubmissionPage.styled.ts
  frontend/src/pages/SubmissionPage.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, 🚀 개선

#297 해시태그 구현 (Issue #287)
  frontend/src/apis/solutions.ts
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailHeader.tsx
  frontend/src/components/MissionList/index.tsx
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Card/index.tsx
  frontend/src/components/common/HashTagButton/HashTagButton.styled.ts
  frontend/src/components/common/HashTagButton/index.tsx
  frontend/src/components/common/InfoCard/InfoCard.styled.ts
  frontend/src/components/common/InfoCard/index.tsx
  frontend/src/hooks/useDragScroll.ts
  frontend/src/mocks/hashTag.json
  frontend/src/mocks/missions.json
  frontend/src/pages/MissionDetailPage.tsx
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/types/index.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#299 대시보드 페이지내에 진행 중인 미션 리스트와 내가 제출한 솔루션 구현 (issue #272)
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/assets/images/NoResult.svg
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.styled.ts
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/DashBoard/SubmittedSolutions/index.tsx
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/components/Mission/index.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useSolutions.ts
  frontend/src/hooks/useSubmittedSolutions.ts
  frontend/src/hooks/useUserInfo.ts
  frontend/src/index.tsx
  frontend/src/mocks/SubmittedSolutions.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missionInProgress.json
  frontend/src/mocks/missions.json
  frontend/src/mocks/submission.json
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/index.tsx
  frontend/src/pages/DashboardPage/MissionInProgress/index.tsx
  frontend/src/pages/DashboardPage/index.tsx
  frontend/src/types/index.ts
  frontend/src/types/mission.ts
  frontend/src/types/solution.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#313 fix: useMissionInProgress 재생성
  frontend/src/apis/missionAPI.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useMissionInProgress.ts
  frontend/src/mocks/missionWithDescription.json
Labels: 🎨 프론트엔드, 🐛 버그

#315 JPA 추상 클래스 적용 (issue #304)
  backend/src/main/java/develup/domain/IdentifiableEntity.java
  backend/src/main/java/develup/domain/hashtag/HashTag.java
  backend/src/main/java/develup/domain/member/Member.java
  backend/src/main/java/develup/domain/mission/Mission.java
  backend/src/main/java/develup/domain/mission/MissionHashTag.java
  backend/src/main/java/develup/domain/solution/Solution.java
  backend/src/main/resources/data.sql
Labels: 🚛 백엔드, 🚀 개선

#308 해시태그 목록 조회 기능 구현(issue #307)
  backend/src/main/java/develup/api/HashTagApi.java
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/application/hashtag/HashTagService.java
  backend/src/test/java/develup/api/ApiTestSupport.java
  backend/src/test/java/develup/api/HashTagApiTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#318 백엔드 main 브랜치 및 prod 서버 도커 도입 (issue #309)
  .github/workflows/backend_cd.yml
  backend/Dockerfile
  backend/compose.yml
Labels: 🚛 백엔드, ⚒️ 기능

#319 해시태그 기반 필터링 기능 구현 (issue #311)
  backend/src/main/java/develup/api/MissionApi.java
  backend/src/main/java/develup/api/SolutionApi.java
  backend/src/main/java/develup/application/mission/MissionService.java
  backend/src/main/java/develup/application/solution/SolutionService.java
  backend/src/main/java/develup/domain/mission/MissionRepository.java
  backend/src/main/java/develup/domain/solution/SolutionRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/develup/api/MissionApiTest.java
  backend/src/test/java/develup/api/SolutionApiTest.java
  backend/src/test/java/develup/application/mission/MissionServiceTest.java
  backend/src/test/java/develup/domain/mission/MissionRepositoryTest.java
  backend/src/test/java/develup/domain/solution/SolutionRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#316 클라이언트단에서 API 중복호출 방지 (issue #305)
  frontend/src/apis/solutions.ts
  frontend/src/constants/messages.ts
  frontend/src/hooks/__tests__/useSingleRequestMutation.test.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useSingleRequest.ts
  frontend/src/hooks/useSingleRequestMutation.ts
  frontend/src/hooks/useSolutions.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/hooks/useUserInfo.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#324 공통 폰트, 그림자 및 컬러 규격 설정 (issue #317)
  frontend/src/components/Carousel/Carousel.styled.ts
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.styled.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/NotiModal/NotiModal.styled.ts
  frontend/src/components/Mission/Mission.styled.ts
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionSubmit/MissionThumbnail.styled.ts
  frontend/src/components/MissionSubmit/MissionTitle.styled.ts
  frontend/src/components/MissionSubmit/OneWord.styled.ts
  frontend/src/components/MissionSubmit/PRLink.styled.ts
  frontend/src/components/MissionSubmit/SubmitBanner.styled.ts
  frontend/src/components/MissionSubmit/SubmitButton.styled.ts
  frontend/src/components/ModalContent/MissionProcess/ModalProcess.styled.ts
  frontend/src/components/PopUp/SubmitSuccessPopUp.styled.ts
  frontend/src/components/Tab/Tab.styled.ts
  frontend/src/components/UserProfile/UserProfile.styled.ts
  frontend/src/components/common/Badge/Badge.styled.ts
  frontend/src/components/common/Badge/index.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Card/Card.styled.ts
  frontend/src/components/common/HashTagButton/HashTagButton.styled.ts
  frontend/src/components/common/InfoCard/InfoCard.styled.ts
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/LoadingSpinner/LoadingSpinner.styled.ts
  frontend/src/components/common/Modal/Modal.styled.ts
  frontend/src/components/common/TextArea/TextArea.styled.ts
  frontend/src/index.tsx
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 🎨 프론트엔드, 🚀 개선

#328 솔루션 상세 페이지 댓글 리스트 및 댓글 생성 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/commentAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/assets/images/default-user.png
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailContent.tsx
  frontend/src/components/SolutionDetail/CommentForm/CommentForm.styled.ts
  frontend/src/components/SolutionDetail/CommentForm/index.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentItem/CommentInfo.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentItem/CommentReplyItem.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentItem/CommentReplyList.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentItem/CommentReplySection.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentItem/index.tsx
  frontend/src/components/SolutionDetail/CommentList/CommentList.styled.ts
  frontend/src/components/SolutionDetail/CommentList/index.tsx
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/common/SanitizedMDPreview.tsx
  frontend/src/hooks/__tests__/useMission.test.tsx
  frontend/src/hooks/__tests__/userPathnameAt.test.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useComments.ts
  frontend/src/hooks/usePathnameAt.ts
  frontend/src/hooks/usePostCommentMutation.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/index.tsx
  frontend/src/pages/SolutionDetailPage.tsx
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/types/index.ts
  frontend/src/utils/formatDateString.ts
  frontend/src/utils/padToTwoDigits.ts
  frontend/src/utils/validate.ts
  frontend/webpack.common.js
Labels: 🎨 프론트엔드, ⚒️ 기능

#321 백엔드 CD 불필요한 작업 제거 (issue #320)
  .github/workflows/backend_cd.yml
Labels: 🚛 백엔드, 🚀 개선

#334 Swagger CORS 오류 해결 (issue #333)
  backend/src/main/java/develup/api/config/SwaggerConfig.java
Labels: 🚛 백엔드, 🐛 버그

#337 프론트엔드 code pipeline buildspec 작성
  frontend/buildspec.yml
Labels: 🎨 프론트엔드, 🚀 개선

#339 buildspec 버전 추가
  frontend/buildspec.yml
Labels: 🎨 프론트엔드, 🐛 버그

#331 내가 작성한 댓글(솔루션) 목록 조회하는 API 구현(issue #326)
  backend/src/main/java/develup/api/SolutionCommentApi.java
  backend/src/main/java/develup/application/solution/comment/MySolutionCommentResponse.java
  backend/src/main/java/develup/application/solution/comment/SolutionCommentService.java
  backend/src/main/java/develup/domain/solution/comment/MySolutionComment.java
  backend/src/main/java/develup/domain/solution/comment/SolutionCommentRepository.java
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
  backend/src/test/java/develup/domain/solution/comment/SolutionCommentRepositoryTest.java
Labels: 🚛 백엔드, ⚒️ 기능

#341 front cd yml 파일 삭제 (issue #340)
  .github/workflows/front_cd.yml
Labels: 🎨 프론트엔드, 🚀 개선

#327 로그아웃 뮤테이션 생성 및 제출시 로직 개선 (issue #306)
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/hooks/useDescription.ts
  frontend/src/hooks/useLogoutMutation.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/utils/extractMissionName.ts
Labels: 🎨 프론트엔드, 🚀 개선

#332 해시태그 버튼 및 필터링 구현 (issue #303)
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/HashTagList/HashTagList.styled.ts
  frontend/src/components/HashTagList/index.tsx
  frontend/src/components/Mission/index.tsx
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/common/HashTagButton/HashTagButton.styled.ts
  frontend/src/components/common/HashTagButton/index.tsx
  frontend/src/constants/hashTags.ts
  frontend/src/hooks/__tests__/useMissions.test.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useHashTags.ts
  frontend/src/hooks/useMissions.ts
  frontend/src/hooks/useSolutionSummaries.ts
  frontend/src/mocks/SubmittedSolutions.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missions.json
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/types/index.ts
  frontend/src/types/mission.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#344 dev / prod에 맞게 백엔드 API URL 수정 (issue #342)
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#346 대시보드 로그인상태에 따라서 분기처리 (issue #345)
  frontend/src/components/Header/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#357 미션 제출 페이지 스타일링 조정 (issue #353)
  .github/workflows/front_cd.yml
  frontend/src/apis/baseUrl.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/HashTagList/HashTagList.styled.ts
  frontend/src/components/HashTagList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Mission/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionList/MissionList.styled.ts
  frontend/src/components/MissionSubmit/SubmitButton.tsx
  frontend/src/components/common/HashTagButton/HashTagButton.styled.ts
  frontend/src/components/common/HashTagButton/index.tsx
  frontend/src/constants/hashTags.ts
  frontend/src/hooks/__tests__/useMissions.test.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useDescription.ts
  frontend/src/hooks/useHashTags.ts
  frontend/src/hooks/useLogoutMutation.ts
  frontend/src/hooks/useMissions.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useSolutionSummaries.ts
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/hooks/useSubmitSolutionMutation.ts
  frontend/src/mocks/SubmittedSolutions.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missions.json
  frontend/src/pages/DashboardPage/DashBoardPageLayout/DashBoardPageLayout.styled.ts
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/MissionListPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/pages/SolutionListPage/index.tsx
  frontend/src/types/index.ts
  frontend/src/types/mission.ts
  frontend/src/utils/extractMissionName.ts
Labels: 🎨 프론트엔드, 🚀 개선

#364 솔루션 상세 페이지 구현 (issue #349)
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/components/SolutionDetail/CommentList/CommentList.styled.ts
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/SolutionDetail/SolutionSection/SolutionDetailHeader.tsx
  frontend/src/components/SolutionDetail/SolutionSection/SolutionSection.styled.ts
  frontend/src/components/SolutionDetail/SolutionSection/index.tsx
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useSolution.ts
  frontend/src/pages/SolutionDetailPage.tsx
  frontend/src/types/solution.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#372 디버깅을 위해 prod 서버 url 분기문 제거 (issue #371)
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, 🐛 버그

#376 대시보드 내부에 내가 작성한 댓글 섹션 생성 (issue #361)
  frontend/src/apis/clients/develupClient.ts
  frontend/src/apis/commentAPI.ts
  frontend/src/apis/missionAPI.ts
  frontend/src/apis/paths.ts
  frontend/src/assets/images/comment-count.svg
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/components/DashBoard/DashBoardMissionList/index.tsx
  frontend/src/components/DashBoard/MyComments/MyComment.tsx
  frontend/src/components/DashBoard/MyComments/MyCommentList.tsx
  frontend/src/components/DashBoard/MyComments/MyComments.styled.ts
  frontend/src/hooks/queries/keys.ts
  frontend/src/hooks/useMyComments.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/missionInProgress.json
  frontend/src/mocks/myComments.json
  frontend/src/pages/DashboardPage/MyComments/index.tsx
  frontend/src/pages/DashboardPage/index.tsx
  frontend/src/types/index.ts
  frontend/src/types/mission.ts
Labels: 🎨 프론트엔드, ⚒️ 기능

#378 msw 환경 해제 (issue #377)
  frontend/src/index.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#381 대시보드 코멘트 페이지 바인딩 (issue #380)
  frontend/src/index.tsx
  frontend/src/pages/DashboardPage/index.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#383 배포 해결을 위해 진행했던 수정사항 롤백 (issue #375)
  frontend/buildspec.yml
  frontend/src/components/SolutionDetail/SolutionSection/index.tsx
  frontend/webpack.common.js
Labels: 🎨 프론트엔드, ⚒️ 기능

#389 about 페이지 구현 (issue #382)
  frontend/src/assets/images/1.svg
  frontend/src/assets/images/2.svg
  frontend/src/assets/images/3.svg
  frontend/src/assets/images/4.svg
  frontend/src/assets/images/5.svg
  frontend/src/assets/images/6.svg
  frontend/src/assets/images/ContentBanner.svg
  frontend/src/constants/routes.ts
  frontend/src/index.tsx
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#387 frontend dev CI 스트립트 추가 (issue #386)
  .github/workflows/frontend_dev_ci.yml
Labels: 🎨 프론트엔드, ⚒️ 기능

#385 코드 보러 가기 버튼 추가 (issue #336)
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#362 compose 파일이 실행하는 profile 변경 (issue #354)
  backend/compose.yml
Labels: 🚛 백엔드, ⚒️ 기능

#365 테스트에서 createdAt을 정확히 검사하지 않도록 변경 (issue #363)
  backend/src/test/java/develup/api/SolutionCommentApiTest.java
Labels: 🚛 백엔드, 🐛 버그

#400 missionList flex-wrap 속성을 wrap으로 설정 (issue: #398)
  frontend/src/components/MissionList/MissionList.styled.ts
Labels: 🎨 프론트엔드, 🐛 버그

#397 모달 컨텐츠 추가 (issue #379)
  frontend/src/assets/images/howToGoRepo.svg
  frontend/src/assets/images/howToLogin.svg
  frontend/src/assets/images/howToReadDocs.svg
  frontend/src/assets/images/howToStart.svg
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/ModalContent/MissionProcess/MissionProcess.styled.ts
  frontend/src/components/ModalContent/MissionProcess/index.tsx
  frontend/src/components/ModalContent/ModalContent.styled.ts
  frontend/src/components/ModalContent/index.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#395 메인 페이지에 캐러셀 연결 (issue #394)
  frontend/src/apis/paths.ts
  frontend/src/apis/solutions.ts
  frontend/src/assets/images/1.png
  frontend/src/assets/images/1.svg
  frontend/src/assets/images/2.png
  frontend/src/assets/images/2.svg
  frontend/src/assets/images/3.png
  frontend/src/assets/images/3.svg
  frontend/src/assets/images/4.png
  frontend/src/assets/images/4.svg
  frontend/src/assets/images/5.png
  frontend/src/assets/images/5.svg
  frontend/src/assets/images/6.png
  frontend/src/components/DashBoard/MyComments/MyComment.tsx
  frontend/src/hooks/useSubmitSolution.ts
  frontend/src/pages/AboutPage/AboutPage.styled.ts
  frontend/src/pages/AboutPage/AboutPage.tsx
  frontend/src/pages/DashboardPage/MyComments/index.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MissionSubmitPage.tsx
Labels: 🎨 프론트엔드, ⚒️ 기능

#402 디자인 고도화 (issue #368)
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/components/DashBoard/MyComments/MyComments.styled.ts
  frontend/src/components/Header/Header.styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/MissionDetail/MissionDetail.styled.ts
  frontend/src/components/MissionDetail/MissionDetailButtons.tsx
  frontend/src/components/MissionSubmit/MissionThumbnail.tsx
  frontend/src/components/MissionSubmit/PRLink.tsx
  frontend/src/components/MissionSubmit/SubmitBanner.styled.ts
  frontend/src/components/MissionSubmit/SubmitButton.styled.ts
  frontend/src/components/SolutionDetail/CommentList/CommentList.styled.ts
  frontend/src/components/SolutionDetail/SolutionDetail.styled.ts
  frontend/src/components/SolutionDetail/SolutionSection/SolutionSection.styled.ts
  frontend/src/components/SolutionDetail/SolutionSection/index.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/TextArea/TextArea.styled.ts
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MissionListPage/MissionListPage.styled.ts
  frontend/src/pages/SolutionListPage/SolutionListPage.styled.ts
  frontend/src/styles/GlobalLayout.tsx
Labels: 🎨 프론트엔드, 🚀 개선

#403 어바웃 페이지 SVG 파일 관련 오류수정 (issue #401)
  frontend/src/assets/images/1.svg
  frontend/src/assets/images/2.svg
  frontend/src/assets/images/3.svg
  frontend/src/assets/images/4.svg
  frontend/src/assets/images/5.svg
  frontend/src/assets/images/ContentBanner.svg
  frontend/src/assets/images/CotentBanner.svg
  frontend/src/pages/AboutPage/AboutPage.tsx
  frontend/src/pages/MainPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#405 svg 파일 오탈자 수정 (issue #404)
  frontend/src/assets/images/ContentBanner.svg
  frontend/src/components/DashBoard/DashBoardMissionList/NoContent.tsx
  frontend/src/pages/MainPage/MainPage.styled.tsx
  frontend/src/pages/MainPage/index.tsx
Labels: 🎨 프론트엔드, 🐛 버그

#409 FE dev conflict 해결
  frontend/src/apis/baseUrl.ts
Labels: 🎨 프론트엔드, 🐛 버그
